export type Chapter = {
  slug: string;
  world: "fundamentals" | "dj" | "producer";
  number: number;
  title: string;
  tagline: string;
  description: string;
  pathSlugs: string[];
  trophy: { slug: string; name: string; description: string };
};

export const CHAPTERS: Chapter[] = [
  // FUNDAMENTALS
  { slug: "sound-science", world: "fundamentals", number: 1, title: "Sound Science", tagline: "Understand what music is physically made of", description: "Frequency, amplitude, timbre, waveforms, overtones, acoustics and how your ears work. The physics of sound is the foundation of every decision you make as a producer or DJ.", pathSlugs: ["acoustics", "perception"], trophy: { slug: "acoustician", name: "Acoustician", description: "Completed Sound Science — you understand what music is made of" } },
  { slug: "rhythm-and-time", world: "fundamentals", number: 2, title: "Rhythm & Time", tagline: "Master the temporal organisation of music", description: "From the basic pulse to polyrhythm, syncopation, groove and note subdivision. Rhythm is the backbone of every genre — this chapter builds your internal clock and your DAW timing vocabulary.", pathSlugs: ["pulse-and-tempo", "groove-and-subdivision"], trophy: { slug: "timekeeper-trophy", name: "Timekeeper", description: "Completed Rhythm & Time — your internal clock is calibrated" } },
  { slug: "melody-and-pitch", world: "fundamentals", number: 3, title: "Melody & Pitch", tagline: "Navigate the world of pitch and scales", description: "Notes, octaves, major and minor scales, intervals, pentatonic shortcuts, how to write a hook, ear training and modal colour. The tools that let you recognise and write any melody.", pathSlugs: ["notes-and-scales", "ear-and-expression"], trophy: { slug: "melodist", name: "Melodist", description: "Completed Melody & Pitch — you can hear and write melodies" } },
  { slug: "harmony-and-chords", world: "fundamentals", number: 4, title: "Harmony & Chords", tagline: "Learn the colour system of music", description: "Triads, chord types, chord progressions, keys and tonality, tension and resolution, harmony in the DAW and song structure. The emotional architecture that makes music feel like something.", pathSlugs: ["chords-and-keys", "music-in-motion"], trophy: { slug: "harmonist", name: "Harmonist", description: "Completed Harmony & Chords — you understand the emotional architecture of music" } },
  { slug: "music-technology", world: "fundamentals", number: 5, title: "Music Technology", tagline: "The tools that turn ideas into recordings", description: "DAWs, MIDI, digital audio, samples and loops, signal chain, effects overview and mixing basics. Every concept here applies whether you produce or DJ. The last chapter before you specialise.", pathSlugs: ["the-digital-studio", "signal-and-mix"], trophy: { slug: "studio-ready", name: "Studio Ready", description: "Completed Music Technology — ready to enter a DAW or DJ booth" } },

  // DJ WORLD
  { slug: "setup-and-culture", world: "dj", number: 1, title: "Setup & Culture", tagline: "Know your roots, gear and software", description: "What DJing is, where it came from, every piece of hardware you'll encounter, how rekordbox fits into the Pioneer DJ ecosystem, headphone cueing, booth signal flow and your first mix. You can't mix well without this foundation.", pathSlugs: ["gear-and-history", "your-first-session"], trophy: { slug: "dj-initiate-chapter", name: "DJ Initiate", description: "Completed Setup & Culture — you know your roots and your rig" } },
  { slug: "the-library", world: "dj", number: 2, title: "The Library", tagline: "Your collection is your instrument", description: "Audio formats, BPM analysis, the Camelot Wheel key system, My Tags, playlist organisation, crate digging, the full EXPORT mode workflow and waveform reading. A great DJ has a great library.", pathSlugs: ["know-your-music", "organise-and-export"], trophy: { slug: "library-curator", name: "Library Curator", description: "Completed The Library — your collection is organised and ready for any gig" } },
  { slug: "the-mix-dj", world: "dj", number: 3, title: "The Mix", tagline: "The technical craft of DJing", description: "Manual beatmatching by ear, the SYNC function, cue points, three-band EQ mixing and the bass swap, crossfader technique, long blends, power cuts and loop-based extensions. This is the engine room of DJing.", pathSlugs: ["beatmatching-fundamentals", "transitions"], trophy: { slug: "blendmaster", name: "Blendmaster", description: "Completed The Mix — your transitions are clean and confident" } },
  { slug: "dj-performance", world: "dj", number: 4, title: "Performance", tagline: "Reading a room and managing energy", description: "Crowd body language, set arc structure, harmonic mixing with the Camelot Wheel, Beat FX with restraint, energy peaks and valleys, your sound identity and the full professional set preparation checklist.", pathSlugs: ["crowd-and-energy", "the-working-dj"], trophy: { slug: "crowd-reader", name: "Crowd Reader", description: "Completed Performance — you can read a room and build a set arc" } },
  { slug: "dj-mastery", world: "dj", number: 5, title: "Mastery", tagline: "From technically competent to artistically distinct", description: "Advanced effects use, hot cue juggling and loop rolls, key shifting with Master Tempo, stem DJing, recording your set, DVS and timecode vinyl, the business of DJing and what it means to develop a unique artistic voice.", pathSlugs: ["advanced-technique-dj", "career-and-identity"], trophy: { slug: "club-ready", name: "Club Ready", description: "Completed DJ Mastery — you have a full professional skill set and artistic identity" } },

  // PRODUCER
  { slug: "first-contact", world: "producer", number: 1, title: "First Contact", tagline: "Get inside Ableton Live and understand how it thinks", description: "The Live mental model, browser, preferences, Session View vs Arrangement View, clip types, tracks, scenes, Follow Actions, Capture MIDI and Take Lanes. The interface vocabulary that unlocks everything else.", pathSlugs: ["the-interface", "clips-and-workflow"], trophy: { slug: "live-initiated", name: "Live Initiated", description: "Completed First Contact — you understand how Ableton Live thinks" } },
  { slug: "sound-and-midi", world: "producer", number: 2, title: "Sound & MIDI", tagline: "Make and shape sounds with every Live instrument and effect", description: "MIDI Piano Roll, all warp modes, recording, comping, slicing, MPE. Every core instrument — Drum Rack, Wavetable, Operator, Sampler/Simpler. Every core effect — EQ Eight, Compressor, Reverb, Delay, Saturator, MIDI Effects, Racks. The full palette.", pathSlugs: ["midi-and-audio", "core-instruments", "core-effects"], trophy: { slug: "sound-sculptor", name: "Sound Sculptor", description: "Completed Sound & MIDI — you can make and shape any sound in Live" } },
  { slug: "the-mix-producer", world: "producer", number: 3, title: "The Mix", tagline: "Balance and shape your full track", description: "Gain staging, sends and returns, group routing, automation lanes, modulation, sidechain compression, Max for Live, Glue Compressor and True Peak limiting. The skills that turn a collection of sounds into a finished track.", pathSlugs: ["mixing-essentials", "advanced-mixing"], trophy: { slug: "mix-engineer", name: "Mix Engineer", description: "Completed The Mix — your tracks sound balanced and finished" } },
  { slug: "performance-and-flow", world: "producer", number: 4, title: "Performance & Flow", tagline: "Take your music off the grid and into the world", description: "Push 3, MIDI mapping, Tempo Following, Ableton Link, CV Tools, Macro Variations, exporting, live sets and project management. Everything between finishing a track and playing it for people.", pathSlugs: ["controllers-and-mapping", "live-output"], trophy: { slug: "performance-ready", name: "Performance Ready", description: "Completed Performance & Flow — you can take your music into any live context" } },
  { slug: "advanced-producer", world: "producer", number: 5, title: "Advanced", tagline: "Deep instruments and Live 12's most powerful features", description: "Sampler deep, Drift, Granulator III, Collision/Tension/Electric/Analog, Bass & Poli, Instrument Rack. Then Live 12's four new devices: Meld, Drum Sampler, Hybrid Reverb, Roar. Then Live 12 power features: stem separation, MIDI Transforms, Scale Awareness and more.", pathSlugs: ["deep-instruments", "live12-devices", "live12-power"], trophy: { slug: "live12-expert", name: "Live 12 Expert", description: "Completed Advanced — you've mastered the deepest instruments and Live 12's full feature set" } },
  { slug: "synthesis", world: "producer", number: 6, title: "Synthesis", tagline: "Build any sound from oscillators, filters and envelopes", description: "How a synth makes sound — oscillators, filters, envelopes, LFOs and modulation. Based on learningsynths.ableton.com. 18 missions across 3 paths: Sound, Shaping, and Movement. Build, bend and design your own bass, leads, pads and plucks.", pathSlugs: ["synth-sound", "synth-shaping", "synth-movement"], trophy: { slug: "synth-architect", name: "Synth Architect", description: "Completed Synthesis — you can design any sound from raw waves" } },
];

export const chapterBySlug = (slug: string) => CHAPTERS.find((c) => c.slug === slug);
export const chaptersByWorld = (world: Chapter["world"]) =>
  CHAPTERS.filter((c) => c.world === world).sort((a, b) => a.number - b.number);

export const WORLD_TROPHIES: Record<string, { slug: string; name: string; description: string }> = {
  fundamentals: { slug: "fundamentals-master", name: "Fundamentals Master", description: "Completed all 5 Fundamentals chapters — you have the vocabulary of music" },
  dj: { slug: "dj-master", name: "DJ Master", description: "Completed all 5 DJ chapters — you are a complete DJ" },
  producer: { slug: "producer-master", name: "Producer Master", description: "Completed all 5 Producer chapters — you have mastered Ableton Live 12" },
};

export const MASTER_TROPHY = {
  slug: "ccd-master",
  name: "CCD Master",
  description: "Completed all three worlds — Fundamentals, DJ and Producer. The full curriculum.",
};
