// Catalogue of devices for the Device Lab route.
import type { ParamSpec, DevicePreset } from "@/components/DeviceLab";
import {
  makeEQ3, makeComp, makeSat, makeReverb, makeDelay, makeAutoFilter, makeChorus,
  makePhaser, makeGlueComp, makeLimiter,
  makeEQ8, makeGate, makeOverdrive, makeErosion, makeRedux, makeFlanger,
  makeVibrato, makeEcho, makeGrainDelay, makeFilterDelay, makeDrumBuss,
  makeAutoPan, makeFreqShift,
  type DeviceNode,
} from "@/lib/audio-bus";
import type { SampleName } from "@/lib/audio";

export type DeviceDef = {
  slug: string;
  name: string;
  category: "EQ" | "DYNAMICS" | "TIME" | "MOD" | "FILTER" | "DRIVE";
  tagline: string;
  what: string;
  how: string;
  factory: () => DeviceNode;
  params: ParamSpec[];
  presets: DevicePreset[];
  listenFor: string[];
  signalFlow: string;
  defaultSample?: SampleName;
  // Phase-1 enrichments — optional so existing entries still type-check.
  whatLong?: string[];                                    // 2–3 plain-English paragraphs
  commonMistakes?: string[];                              // top 3
  workedExample?: { goal: string; steps: string[]; preset?: string };
  related?: { devices?: string[]; missions?: string[] };
  source?: string;                                         // "Live 12 manual §X.Y"
};

export const DEVICES: DeviceDef[] = [
  {
    slug: "eq",
    defaultSample: "full-mix",
    name: "EQ Three",
    category: "EQ",
    tagline: "Turn lows, mids and highs up or down.",
    what: "Sound is made of low, middle and high frequencies. EQ lets you turn any of them up or down. Too boomy? Lower the lows. Too dull? Raise the highs.",
    how: "Three volume controls, one per band. Move a knob up to boost that range, down to cut it. Cutting usually sounds cleaner than boosting — try cuts first.",
    factory: makeEQ3,
    params: [
      { kind: "knob", id: "low", label: "LOW", min: -18, max: 18, default: 0, unit: "dB", explain: "Bass and kick weight. Lower if it's boomy." },
      { kind: "knob", id: "mid", label: "MID", min: -18, max: 18, default: 0, unit: "dB", explain: "Vocals, snare, guitar live here. Most of the music." },
      { kind: "knob", id: "midFreq", label: "MID FREQ", min: 200, max: 6000, default: 1000, unit: "Hz", explain: "Picks which middle range you're tweaking." },
      { kind: "knob", id: "midQ", label: "MID Q", min: 0.3, max: 8, default: 1, explain: "Wide = musical. Narrow = pinpoint a problem." },
      { kind: "knob", id: "hi", label: "HIGH", min: -18, max: 18, default: 0, unit: "dB", explain: "Air, sparkle, cymbals. Raise for brightness." },
    ],
    presets: [
      { name: "★ PHONE FILTER", values: { low: -18, mid: 12, midFreq: 2000, midQ: 6, hi: -18 } },
      { name: "TOO BOOMY", values: { low: -8, mid: 0, hi: 0 } },
      { name: "AIR & SPARKLE", values: { low: 0, mid: 0, hi: 6 } },
      { name: "VOCAL CARVE", values: { low: 0, mid: -6, midFreq: 700, midQ: 4, hi: 0 } },
      { name: "FLAT", values: { low: 0, mid: 0, hi: 0, midFreq: 1000, midQ: 1 } },
    ],
    listenFor: [
      "Sweep MID FREQ with +12 dB Q=8 — that screech reveals problem frequencies.",
      "A/B with B button: subtractive EQ should make the source clearer, not louder.",
      "Boomy lows on chord pad? Cut LOW -8 dB.",
    ],
    signalFlow: "SOURCE → LOW SHELF → MID PEAK → HIGH SHELF → OUT",
  },
  {
    slug: "compressor",
    defaultSample: "drum-loop",
    name: "Compressor",
    category: "DYNAMICS",
    tagline: "Make loud parts quieter so the whole thing feels bigger.",
    what: "A compressor automatically turns down anything that's too loud. The quiet parts then feel louder by comparison. Vocals stay present, drums punch, mixes glue together.",
    how: "It listens for sound above the THRESHOLD and cranks it down by the RATIO. ATTACK and RELEASE control how fast it reacts. MAKEUP brings the level back up.",
    factory: makeComp,
    params: [
      { kind: "knob", id: "threshold", label: "THRESHOLD", min: -60, max: 0, default: -20, unit: "dB", explain: "The 'too loud' line. Anything above gets pushed down." },
      { kind: "knob", id: "ratio", label: "RATIO", min: 1, max: 20, default: 4, unit: ":1", explain: "How hard it pushes down. 1=off, 4=glue, 10+=brickwall." },
      { kind: "knob", id: "attack", label: "ATTACK", min: 0, max: 1, step: 0.005, default: 0.01, unit: "s", explain: "How fast it reacts. Slow = punchier drums." },
      { kind: "knob", id: "release", label: "RELEASE", min: 0.01, max: 1, step: 0.01, default: 0.25, unit: "s", explain: "How fast it lets go. Match the song's groove." },
      { kind: "knob", id: "knee", label: "KNEE", min: 0, max: 40, default: 6, unit: "dB", explain: "Soft = gentle and invisible. Hard = obvious squash." },
      { kind: "knob", id: "makeup", label: "MAKEUP", min: 0.5, max: 4, step: 0.05, default: 1.4, unit: "x", explain: "Volume back up after squashing. A/B at the same loudness." },
    ],
    presets: [
      { name: "★ EXTREME SQUASH", values: { threshold: -45, ratio: 20, attack: 0.001, release: 0.4, knee: 0, makeup: 3 } },
      { name: "DRUM PUNCH", values: { threshold: -18, ratio: 4, attack: 0.02, release: 0.15, knee: 4, makeup: 1.6 } },
      { name: "VOCAL GLUE", values: { threshold: -22, ratio: 3, attack: 0.005, release: 0.2, knee: 12, makeup: 1.5 } },
      { name: "MIX BUS", values: { threshold: -12, ratio: 2, attack: 0.03, release: 0.3, knee: 12, makeup: 1.2 } },
      { name: "PUMP", values: { threshold: -30, ratio: 10, attack: 0.001, release: 0.5, knee: 0, makeup: 2 } },
    ],
    listenFor: [
      "Toggle A/B — compressed should feel more even, not just louder.",
      "Crank the threshold down, listen for breathing/pumping artefacts.",
      "Slow the attack to ~30 ms on drums to let transients punch through.",
    ],
    signalFlow: "SOURCE → DETECTOR(threshold) → GAIN REDUCTION → MAKEUP → OUT",
  },
  {
    slug: "saturator",
    defaultSample: "full-mix",
    name: "Saturator",
    category: "DRIVE",
    tagline: "Warmth, grit or full destruction.",
    what: "Saturation adds new harmonics that weren't there. A little = warmth and weight. A lot = dirt and distortion. The TYPE picks the flavour (tape, tube, digital…).",
    how: "DRIVE pushes the signal harder into a shaping curve. The curve bends the loud parts and creates new overtones. OUTPUT keeps the volume sane.",
    factory: makeSat,
    params: [
      { kind: "knob", id: "drive", label: "DRIVE", min: -12, max: 36, step: 0.5, default: 0, unit: "dB", explain: "How hard you push. 0 = clean, +24 = nasty." },
      { kind: "select", id: "type", label: "TYPE", options: [
        { value: "analog", label: "ANALOG" }, { value: "soft", label: "SOFT SINE" },
        { value: "medium", label: "MEDIUM" }, { value: "hard", label: "HARD" },
        { value: "sinoid", label: "SINOID FOLD" }, { value: "digital", label: "DIGITAL" },
      ], default: "analog", explain: "Flavour of distortion. Analog = warm. Hard = clip. Digital = crunchy." },
      { kind: "knob", id: "output", label: "OUTPUT", min: 0, max: 2, step: 0.01, default: 0.7, explain: "Volume after the dirt. Match A/B loudness." },
    ],
    presets: [
      { name: "★ MELT", values: { drive: 30, type: "sinoid", output: 0.4 } },
      { name: "WARM GLUE", values: { drive: 6, type: "analog", output: 0.7 } },
      { name: "TAPE COLOUR", values: { drive: 12, type: "medium", output: 0.6 } },
      { name: "BROKEN", values: { drive: 24, type: "hard", output: 0.4 } },
      { name: "BITCRUSH", values: { drive: 18, type: "digital", output: 0.5 } },
    ],
    listenFor: [
      "On chords: SOFT @ 0.2 thickens. SOFT @ 0.8 gets fuzzy and loud.",
      "On drums: HARD @ 0.5 adds aggression, attitude.",
      "DIGITAL collapses the bit depth — listen for stair-step grit.",
      "Always A/B match loudness with OUTPUT before judging.",
    ],
    signalFlow: "SOURCE → PRE-GAIN → WAVESHAPER → POST-GAIN → OUT",
  },
  {
    slug: "reverb",
    defaultSample: "chord-pad",
    name: "Reverb",
    category: "TIME",
    tagline: "Put a sound in a room — closet or cathedral.",
    what: "Reverb is what a room does to sound: lots of tiny reflections fading out. Short = real and close. Long = epic and far. It glues elements and adds depth.",
    how: "SIZE sets the room size. DECAY sets how long the tail takes to fade. PREDELAY puts a small gap first, so the dry sound stays clear. WET = how much you hear.",
    factory: makeReverb,
    params: [
      { kind: "knob", id: "size", label: "SIZE", min: 0.1, max: 5, step: 0.05, default: 1.5, unit: "s", explain: "How big the room is." },
      { kind: "knob", id: "decay", label: "DECAY", min: 0.5, max: 6, step: 0.1, default: 2, explain: "How long the tail lasts." },
      { kind: "knob", id: "predelay", label: "PREDELAY", min: 0, max: 200, step: 1, default: 10, unit: "ms", explain: "Tiny gap before the reverb starts. Keeps vocals clear." },
      { kind: "knob", id: "wet", label: "WET", min: 0, max: 1, step: 0.01, default: 0.4, explain: "How much reverb vs. dry sound." },
    ],
    presets: [
      { name: "★ CATHEDRAL", values: { size: 5, decay: 6, predelay: 20, wet: 1 } },
      { name: "TIGHT ROOM", values: { size: 0.4, decay: 1, predelay: 5, wet: 0.3 } },
      { name: "VOCAL HALL", values: { size: 2.5, decay: 3, predelay: 30, wet: 0.35 } },
      { name: "INFINITE PAD", values: { size: 5, decay: 6, predelay: 50, wet: 0.7 } },
      { name: "SLAP", values: { size: 0.15, decay: 0.7, predelay: 80, wet: 0.5 } },
    ],
    listenFor: [
      "Use predelay to keep vocals upfront even with long decay.",
      "Sends > inserts: put reverb on a return so multiple tracks share the same space.",
      "Pre-EQ the send (cut lows under 200 Hz) to stop muddy reverb.",
    ],
    signalFlow: "SOURCE → PREDELAY → CONVOLVER(IR) → WET MIX → OUT",
  },
  {
    slug: "delay",
    defaultSample: "vox-chop",
    name: "Delay",
    category: "TIME",
    tagline: "Repeats. Echoes. Dub madness.",
    what: "A delay repeats the sound after a short gap. Each repeat can be quieter, darker, and trigger another repeat. Set to the song's tempo it becomes rhythmic.",
    how: "TIME sets the gap. FEEDBACK sets how many repeats. TONE darkens each echo. WET sets how loud the echoes are vs. the original.",
    factory: makeDelay,
    params: [
      { kind: "knob", id: "time", label: "TIME", min: 0.05, max: 1.5, step: 0.005, default: 0.375, unit: "s", explain: "Gap between repeats." },
      { kind: "knob", id: "feedback", label: "FEEDBACK", min: 0, max: 0.95, step: 0.01, default: 0.4, explain: "How many echoes. Past ~0.9 it never stops." },
      { kind: "knob", id: "tone", label: "TONE", min: 200, max: 12000, step: 50, default: 4000, unit: "Hz", explain: "Each echo gets darker. Lower = warmer dub." },
      { kind: "knob", id: "wet", label: "WET", min: 0, max: 1, step: 0.01, default: 0.4, explain: "Loudness of the echoes vs. the dry sound." },
    ],
    presets: [
      { name: "★ DUB SIREN", values: { time: 0.4, feedback: 0.88, tone: 1800, wet: 0.9 } },
      { name: "DOTTED 1/8", values: { time: 0.375, feedback: 0.45, tone: 5000, wet: 0.4 } },
      { name: "DUB ECHO", values: { time: 0.5, feedback: 0.7, tone: 1500, wet: 0.5 } },
      { name: "SLAPBACK", values: { time: 0.12, feedback: 0.1, tone: 8000, wet: 0.35 } },
      { name: "SELF-OSC", values: { time: 0.2, feedback: 0.92, tone: 3000, wet: 0.5 } },
    ],
    listenFor: [
      "Set feedback >0.9 then twist time — that's the dub-siren sound.",
      "Drop tone to 1.5 kHz: each echo gets warmer and further away.",
      "On vocals: short slapback (~120 ms) adds depth without muddying.",
    ],
    signalFlow: "SOURCE → DELAY LINE → LOWPASS → FEEDBACK ↻ → WET MIX → OUT",
  },
  {
    slug: "auto-filter",
    defaultSample: "chord-pad",
    name: "Auto Filter",
    category: "FILTER",
    tagline: "A sweeping filter that wahs and wobbles.",
    what: "A filter removes frequencies above or below a point called the cutoff. RESONANCE makes the cutoff sing — that's the classic wah and acid sound.",
    how: "Move the CUTOFF up to brighten, down to muffle. RESONANCE adds emphasis. The LFO sweeps the cutoff back and forth on its own.",
    factory: makeAutoFilter,
    params: [
      { kind: "knob", id: "cutoff", label: "CUTOFF", min: 80, max: 12000, step: 10, default: 2000, unit: "Hz", explain: "Where the filter cuts. Higher = brighter." },
      { kind: "knob", id: "Q", label: "RESONANCE", min: 0.3, max: 20, step: 0.1, default: 1, explain: "Emphasis at the cutoff. High = whistly, acid." },
      { kind: "knob", id: "lfoRate", label: "LFO RATE", min: 0.05, max: 10, step: 0.05, default: 1, unit: "Hz", explain: "How fast the auto-sweep moves." },
      { kind: "knob", id: "lfoDepth", label: "LFO DEPTH", min: 0, max: 4000, step: 10, default: 0, unit: "Hz", explain: "How wide the auto-sweep is." },
      { kind: "knob", id: "envAmt", label: "ENV AMT", min: 0, max: 8000, step: 50, default: 0, unit: "Hz", explain: "Loud sounds open the filter. Makes drums feel alive." },
      { kind: "select", id: "type", label: "TYPE", options: [
        { value: "lowpass", label: "LOW-PASS" }, { value: "highpass", label: "HIGH-PASS" },
        { value: "bandpass", label: "BAND-PASS" }, { value: "notch", label: "NOTCH" },
      ], default: "lowpass", explain: "Which part of the sound passes through." },
    ],
    presets: [
      { name: "★ ACID SWEEP", values: { cutoff: 600, Q: 18, lfoRate: 1, lfoDepth: 3000, type: "lowpass" } },
      { name: "ACID", values: { cutoff: 800, Q: 14, lfoRate: 2, lfoDepth: 1500, type: "lowpass" } },
      { name: "DUB CHORDS", values: { cutoff: 1200, Q: 1, lfoRate: 0.25, lfoDepth: 800, type: "lowpass" } },
      { name: "TELEPHONE", values: { cutoff: 2500, Q: 1, lfoRate: 0, lfoDepth: 0, type: "bandpass" } },
      { name: "OPEN", values: { cutoff: 12000, Q: 0.7, lfoRate: 0, lfoDepth: 0, type: "lowpass" } },
    ],
    listenFor: [
      "Crank Q to 14, sweep cutoff slowly — you can almost play notes.",
      "Slow LFO + wide depth = breathing dub chords.",
      "Highpass on a kick removes weight; useful before reverb sends.",
    ],
    signalFlow: "SOURCE → BIQUAD(cutoff,Q) → OUT  (LFO → cutoff)",
  },
  {
    slug: "chorus",
    defaultSample: "chord-pad",
    name: "Chorus",
    category: "MOD",
    tagline: "One sound becomes many — wide and lush.",
    what: "Chorus makes one instrument sound like several playing together. It's the lush, wide '80s synth and clean-guitar sound.",
    how: "It mixes the dry sound with a slightly-delayed, pitch-wobbling copy. RATE = wobble speed. DEPTH = wobble size. WET = how thick.",
    factory: makeChorus,
    params: [
      { kind: "knob", id: "rate", label: "RATE", min: 0.1, max: 5, step: 0.05, default: 1.2, unit: "Hz", explain: "Speed of the wobble." },
      { kind: "knob", id: "depth", label: "DEPTH", min: 0, max: 20, step: 0.1, default: 5, unit: "ms", explain: "How big the wobble." },
      { kind: "knob", id: "wet", label: "WET", min: 0, max: 1, step: 0.01, default: 0.5, explain: "How much of the chorus you hear." },
    ],
    presets: [
      { name: "★ SEASICK MAX", values: { rate: 5, depth: 20, wet: 1 } },
      { name: "SUBTLE WIDEN", values: { rate: 0.6, depth: 2, wet: 0.35 } },
      { name: "80s LUSH", values: { rate: 1.2, depth: 8, wet: 0.6 } },
      { name: "SEASICK", values: { rate: 4, depth: 18, wet: 0.7 } },
    ],
    listenFor: [
      "Compare A/B — chorus widens but can blur transients.",
      "Slow rate + small depth = thickening. Fast rate = wobble.",
    ],
    signalFlow: "SOURCE → MOD-DELAY → SUM(dry) → OUT  (LFO → delay time)",
  },
  {
    slug: "phaser",
    defaultSample: "chord-pad",
    name: "Phaser",
    category: "MOD",
    tagline: "Swirly, jet-engine sweep through the mids.",
    what: "Phaser creates a moving 'whoosh' across the sound. Famous on funk guitars, electric pianos and drums.",
    how: "It sweeps notches up and down through the spectrum. RATE = sweep speed. DEPTH = how far it travels. FEEDBACK = how sharp the swirl.",
    factory: makePhaser,
    params: [
      { kind: "knob", id: "rate", label: "RATE", min: 0.05, max: 8, step: 0.05, default: 0.5, unit: "Hz", explain: "Sweep speed." },
      { kind: "knob", id: "depth", label: "DEPTH", min: 100, max: 3000, step: 50, default: 600, unit: "Hz", explain: "How far the swirl travels." },
      { kind: "knob", id: "feedback", label: "FEEDBACK", min: 0, max: 0.9, step: 0.01, default: 0.3, explain: "Sharper, deeper swirl." },
      { kind: "knob", id: "wet", label: "WET", min: 0, max: 1, step: 0.01, default: 0.5, explain: "Effect mix." },
    ],
    presets: [
      { name: "★ JET WHOOSH", values: { rate: 0.5, depth: 2800, feedback: 0.85, wet: 1 } },
      { name: "JET", values: { rate: 0.3, depth: 1500, feedback: 0.7, wet: 0.6 } },
      { name: "SUBTLE SWIRL", values: { rate: 0.15, depth: 400, feedback: 0.2, wet: 0.4 } },
      { name: "FAST WAH", values: { rate: 4, depth: 1200, feedback: 0.5, wet: 0.5 } },
    ],
    listenFor: [
      "A/B — phaser adds movement without changing pitch.",
      "Crank feedback for the classic 70s funk-rock swirl.",
      "Slow rate + wet 0.5 = lush moving pad.",
    ],
    signalFlow: "SOURCE → ALLPASS×4 (LFO mod) → SUM(dry) → OUT",
  },
  {
    slug: "glue-compressor",
    defaultSample: "full-mix",
    name: "Glue Compressor",
    category: "DYNAMICS",
    tagline: "Makes a mix feel like one thing instead of many.",
    what: "A compressor tuned for whole mixes and drum buses. It glues separate parts into one cohesive, 'finished' sound. The secret on most records.",
    how: "Same idea as a normal compressor, but gentle and slow on purpose. Aim for just 1–3 dB of gain reduction on the loudest bits.",
    factory: makeGlueComp,
    params: [
      { kind: "knob", id: "threshold", label: "THRESHOLD", min: -30, max: 0, default: -12, unit: "dB", explain: "Where the squash starts." },
      { kind: "knob", id: "ratio", label: "RATIO", min: 1.5, max: 4, step: 0.1, default: 2, unit: ":1", explain: "How hard. Bus comp lives at 2:1 or 4:1." },
      { kind: "knob", id: "attack", label: "ATTACK", min: 0.005, max: 0.1, step: 0.005, default: 0.03, unit: "s", explain: "Slow keeps the punch." },
      { kind: "knob", id: "release", label: "RELEASE", min: 0.05, max: 0.6, step: 0.01, default: 0.25, unit: "s", explain: "Match the song's pulse." },
      { kind: "knob", id: "makeup", label: "MAKEUP", min: 1, max: 2.5, step: 0.05, default: 1.25, unit: "x", explain: "Volume back up. A/B at the same loudness." },
    ],
    presets: [
      { name: "★ HEAR THE GLUE", values: { threshold: -22, ratio: 4, attack: 0.03, release: 0.2, makeup: 1.8 } },
      { name: "MIX BUS GLUE", values: { threshold: -12, ratio: 2, attack: 0.03, release: 0.25, makeup: 1.25 } },
      { name: "DRUM BUS PUNCH", values: { threshold: -10, ratio: 4, attack: 0.01, release: 0.15, makeup: 1.5 } },
      { name: "HARD GLUE", values: { threshold: -18, ratio: 4, attack: 0.005, release: 0.1, makeup: 1.6 } },
    ],
    listenFor: [
      "A/B — should barely hear difference. That's correct.",
      "Aim for 1–3 dB gain reduction on peaks only.",
      "Without it, the mix feels separated and amateur.",
    ],
    signalFlow: "MIX → DETECTOR → SLOW COMP → MAKEUP → OUT",
  },
  {
    slug: "limiter",
    defaultSample: "full-mix",
    name: "Limiter",
    category: "DYNAMICS",
    tagline: "A brick wall. Nothing gets past the ceiling.",
    what: "A limiter guarantees the sound never goes above a chosen volume. It's the last thing in a mix, used to make tracks loud without distorting.",
    how: "INPUT GAIN pushes the sound up. The limiter slams the loudest peaks down so the OUTPUT never crosses the CEILING. Push more = louder, but pumpier.",
    factory: makeLimiter,
    params: [
      { kind: "knob", id: "gain", label: "INPUT GAIN", min: 1, max: 6, step: 0.05, default: 1, unit: "x", explain: "Pushes the sound in harder. Louder, but watch for pumping." },
      { kind: "knob", id: "ceiling", label: "CEILING", min: -12, max: 0, default: -1, unit: "dB", explain: "The maximum output. Sound can never go above this." },
      { kind: "knob", id: "release", label: "RELEASE", min: 0.01, max: 0.3, step: 0.01, default: 0.05, unit: "s", explain: "How fast it lets go. Faster = louder, pumpier." },
    ],
    presets: [
      { name: "★ SLAMMED", values: { gain: 6, ceiling: -0.3, release: 0.02 } },
      { name: "MASTERING", values: { gain: 1.5, ceiling: -1, release: 0.05 } },
      { name: "LOUD AS HELL", values: { gain: 4, ceiling: -0.3, release: 0.02 } },
      { name: "TRANSPARENT", values: { gain: 1.2, ceiling: -2, release: 0.15 } },
    ],
    listenFor: [
      "Push input gain — track gets louder until distortion appears.",
      "Compare commercial mix loudness with and without limiter.",
      "Too much = lifeless, pumping wall of sound.",
    ],
    signalFlow: "MIX → INPUT GAIN → BRICK-WALL COMP → CEILING → OUT",
  },
  // ============================================================
  // PHASE 1 — additional devices to round the catalogue to 22.
  // ============================================================
  {
    slug: "eq-eight",
    defaultSample: "full-mix",
    name: "EQ Eight",
    category: "EQ",
    tagline: "Eight surgical bands. The serious EQ.",
    what: "EQ Eight gives you eight bands of fully-shapeable EQ. The big brother of EQ Three: same idea (boost or cut) but with eight surgical bands and a visual response curve.",
    how: "Each band has frequency, gain and Q. Low and high bands act as shelves; the inner six are bell peaks. Cut narrow to fix problems, boost wide to shape tone.",
    factory: makeEQ8,
    params: [
      { kind: "knob", id: "b0g", label: "LOW SHELF", min: -18, max: 18, default: 0, unit: "dB", explain: "Sub & kick weight." },
      { kind: "knob", id: "b1g", label: "BAND 2", min: -18, max: 18, default: 0, unit: "dB", explain: "150 Hz — bass body." },
      { kind: "knob", id: "b2g", label: "BAND 3", min: -18, max: 18, default: 0, unit: "dB", explain: "350 Hz — boxiness lives here." },
      { kind: "knob", id: "b3g", label: "BAND 4", min: -18, max: 18, default: 0, unit: "dB", explain: "800 Hz — warmth & honk." },
      { kind: "knob", id: "b4g", label: "BAND 5", min: -18, max: 18, default: 0, unit: "dB", explain: "1.8 k — vocal presence." },
      { kind: "knob", id: "b5g", label: "BAND 6", min: -18, max: 18, default: 0, unit: "dB", explain: "4 k — bite & clarity." },
      { kind: "knob", id: "b6g", label: "BAND 7", min: -18, max: 18, default: 0, unit: "dB", explain: "8 k — sparkle & sibilance." },
      { kind: "knob", id: "b7g", label: "HIGH SHELF", min: -18, max: 18, default: 0, unit: "dB", explain: "12 k+ — air." },
    ],
    presets: [
      { name: "★ SMILE", values: { b0g: 4, b1g: 0, b2g: -3, b3g: -3, b4g: 0, b5g: 2, b6g: 4, b7g: 5 } },
      { name: "VOCAL CARVE", values: { b0g: -3, b1g: 0, b2g: -4, b3g: -2, b4g: 3, b5g: 2, b6g: 0, b7g: 2 } },
      { name: "BASS TIGHTEN", values: { b0g: 2, b1g: -2, b2g: -3, b3g: 0, b4g: 0, b5g: 0, b6g: 0, b7g: 0 } },
      { name: "FLAT", values: { b0g: 0, b1g: 0, b2g: 0, b3g: 0, b4g: 0, b5g: 0, b6g: 0, b7g: 0 } },
    ],
    listenFor: ["Cut more than boost.", "Each cut should make the source clearer, not just darker.", "Solo a band, sweep, find the ugly — then cut it."],
    signalFlow: "SRC → SHELF → 6×BELL → SHELF → OUT",
    commonMistakes: ["Boosting everything", "Q too high on boosts", "Forgetting to A/B match loudness"],
    workedExample: { goal: "Carve space for vocals in a busy mix", steps: ["Cut 350 Hz -3 dB on the music", "Cut 1.8 k on the music to leave room", "Boost 4 k on the vocal +2 dB"], preset: "VOCAL CARVE" },
    related: { devices: ["eq", "compressor"], missions: ["mixing-eq"] },
    source: "Live 12 manual §22.10",
  },
  {
    slug: "gate",
    defaultSample: "drum-loop",
    name: "Gate",
    category: "DYNAMICS",
    tagline: "Cuts the silence. Keeps the hits.",
    what: "A gate stays closed (silent) until the input crosses a threshold, then snaps open. Use it to remove bleed between drum hits or to shape long sustains into stutters.",
    how: "Set THRESHOLD just above the noise floor. Anything quieter is muted; anything louder passes. ATTACK opens, RELEASE closes.",
    factory: makeGate,
    params: [
      { kind: "knob", id: "threshold", label: "THRESHOLD", min: -80, max: 0, default: -40, unit: "dB", explain: "Below this = silent. Above = open." },
      { kind: "knob", id: "attack", label: "ATTACK", min: 0.001, max: 0.1, step: 0.001, default: 0.005, unit: "s", explain: "How fast it opens." },
      { kind: "knob", id: "release", label: "RELEASE", min: 0.005, max: 1, step: 0.005, default: 0.1, unit: "s", explain: "How fast it closes." },
    ],
    presets: [
      { name: "★ HARD GATE", values: { threshold: -20, attack: 0.001, release: 0.05 } },
      { name: "DRUM TIGHTEN", values: { threshold: -30, attack: 0.002, release: 0.1 } },
      { name: "GENTLE", values: { threshold: -50, attack: 0.01, release: 0.2 } },
    ],
    listenFor: ["Set threshold so kick triggers but cymbal bleed doesn't.", "Too fast a release = chops the tail.", "Too high a threshold = chops the start of soft hits."],
    signalFlow: "SRC → DETECTOR → VCA(open/close) → OUT",
    commonMistakes: ["Threshold so high it kills soft hits", "Release too fast — chatters", "Using gate where editing would be cleaner"],
    related: { devices: ["compressor"], missions: ["mixing-compression"] },
    source: "Live 12 manual §22.13",
  },
  {
    slug: "overdrive",
    defaultSample: "bass-loop",
    name: "Overdrive",
    category: "DRIVE",
    tagline: "Guitar-amp style dirt.",
    what: "Overdrive shapes the loud parts of the signal aggressively, the way a cranked guitar amp does. Crunchy, present, in-your-face.",
    how: "DRIVE pushes the signal harder into a soft-clipping tanh curve. TONE darkens or brightens the result.",
    factory: makeOverdrive,
    params: [
      { kind: "knob", id: "drive", label: "DRIVE", min: 0, max: 1, step: 0.01, default: 0.3, explain: "How hard it pushes. 0 = clean." },
      { kind: "knob", id: "tone", label: "TONE", min: 500, max: 12000, step: 50, default: 4000, unit: "Hz", explain: "Lower = darker, fuzzier. Higher = bright." },
      { kind: "knob", id: "output", label: "OUTPUT", min: 0, max: 2, step: 0.01, default: 0.6, explain: "Volume after the dirt." },
    ],
    presets: [
      { name: "★ AMP STACK", values: { drive: 0.85, tone: 3000, output: 0.5 } },
      { name: "WARM CRUNCH", values: { drive: 0.3, tone: 5000, output: 0.6 } },
      { name: "FUZZ", values: { drive: 0.95, tone: 1500, output: 0.5 } },
    ],
    listenFor: ["Overdrive on bass thickens it AND adds presence in the mids.", "Too much tone = harsh."],
    signalFlow: "SRC → DRIVE → TANH SHAPER → TONE LP → OUT",
    commonMistakes: ["Drive maxed without tone control", "Forgetting OUTPUT compensation"],
    related: { devices: ["saturator"], missions: [] },
    source: "Live 12 manual §22.30",
  },
  {
    slug: "erosion",
    defaultSample: "vox-chop",
    name: "Erosion",
    category: "DRIVE",
    tagline: "Digital decay & sci-fi grit.",
    what: "Erosion modulates a tiny delay with a sine or noise to introduce subtle digital artefacts — a cheap, lo-fi, alien sheen.",
    how: "It mixes the dry signal with a copy delayed by a few microseconds, modulated very fast. The interaction creates comb-filter and aliasing-style artefacts.",
    factory: makeErosion,
    params: [
      { kind: "knob", id: "freq", label: "FREQUENCY", min: 20, max: 4000, step: 1, default: 80, unit: "Hz", explain: "Sets the artefact pitch." },
      { kind: "knob", id: "width", label: "WIDTH", min: 0.05, max: 5, step: 0.05, default: 0.6, explain: "How wild the modulation is." },
      { kind: "knob", id: "amount", label: "AMOUNT", min: 0, max: 1, step: 0.01, default: 0.4, explain: "How much of the destroyed signal you hear." },
    ],
    presets: [
      { name: "★ FULL DESTROY", values: { freq: 1500, width: 4, amount: 1 } },
      { name: "SUBTLE GRIT", values: { freq: 60, width: 0.3, amount: 0.25 } },
      { name: "ALIEN PHONE", values: { freq: 800, width: 1.5, amount: 0.7 } },
    ],
    listenFor: ["High freq + low amount = subtle texture.", "Low freq + high width = detuned-sounding."],
    signalFlow: "SRC → MOD-DELAY → MIX(dry+wet) → OUT",
    commonMistakes: ["Cranking everything until it just sounds noisy"],
    source: "Live 12 manual §22.16",
  },
  {
    slug: "redux",
    defaultSample: "drum-loop",
    name: "Redux",
    category: "DRIVE",
    tagline: "Bitcrush & sample-rate reduce.",
    what: "Redux destroys digital resolution on purpose. BIT DEPTH crushes the volume steps; DOWNSAMPLE shaves off the high-frequency detail. Lo-fi, retro, broken.",
    how: "It quantises every sample to a small number of steps (bitcrush) and then cuts highs to mimic a lower sample rate.",
    factory: makeRedux,
    params: [
      { kind: "knob", id: "bits", label: "BIT DEPTH", min: 1, max: 16, step: 1, default: 8, explain: "Lower = more crunch & noise." },
      { kind: "knob", id: "downsample", label: "DOWNSAMPLE", min: 1, max: 30, step: 1, default: 1, explain: "Higher = darker, more aliased." },
    ],
    presets: [
      { name: "★ NES BREAK", values: { bits: 4, downsample: 12 } },
      { name: "GAMEBOY", values: { bits: 4, downsample: 6 } },
      { name: "LO-FI WARM", values: { bits: 10, downsample: 3 } },
      { name: "BROKEN PHONE", values: { bits: 6, downsample: 8 } },
    ],
    listenFor: ["On drums: makes them dirty and forward.", "On chords: turns lush pads into 8-bit hell."],
    signalFlow: "SRC → BITCRUSH → LOWPASS (downsample sim) → OUT",
    commonMistakes: ["Bit depth at 1 — just noise"],
    source: "Live 12 manual §22.31",
  },
  {
    slug: "flanger",
    defaultSample: "chord-pad",
    name: "Flanger",
    category: "MOD",
    tagline: "Jet-engine sweeping comb filter.",
    what: "Flanger is like chorus's louder, more dramatic cousin. It mixes the dry signal with a very-short modulated delay, creating a swooshing comb-filter sweep.",
    how: "A delay of ~5 ms is modulated by an LFO. The delayed copy combines with the dry signal — the cancellations and reinforcements move with the LFO.",
    factory: makeFlanger,
    params: [
      { kind: "knob", id: "rate", label: "RATE", min: 0.05, max: 8, step: 0.05, default: 0.4, unit: "Hz", explain: "Sweep speed." },
      { kind: "knob", id: "depth", label: "DEPTH", min: 0.5, max: 8, step: 0.1, default: 3, unit: "ms", explain: "How wide the swoosh." },
      { kind: "knob", id: "feedback", label: "FEEDBACK", min: 0, max: 0.9, step: 0.01, default: 0.5, explain: "Sharper, more obvious." },
      { kind: "knob", id: "wet", label: "WET", min: 0, max: 1, step: 0.01, default: 0.7, explain: "Mix amount." },
    ],
    presets: [
      { name: "★ JET PLANE", values: { rate: 0.3, depth: 7, feedback: 0.85, wet: 1 } },
      { name: "SUBTLE SHIMMER", values: { rate: 0.2, depth: 1, feedback: 0.2, wet: 0.4 } },
      { name: "FUNK GUITAR", values: { rate: 1.5, depth: 3, feedback: 0.5, wet: 0.6 } },
    ],
    listenFor: ["Crank feedback for the classic 70s sweep.", "Slow rate + high depth = slow, wide whoosh."],
    signalFlow: "SRC → MOD-DELAY (LFO) ⟲ FEEDBACK → MIX(dry) → OUT",
    commonMistakes: ["Confusing flanger with chorus — flanger has feedback and shorter delay"],
    related: { devices: ["chorus", "phaser"] },
    source: "Live 12 manual §22.18",
  },
  {
    slug: "vibrato",
    defaultSample: "chord-pad",
    name: "Vibrato",
    category: "MOD",
    tagline: "Pure pitch wobble — no chorus.",
    what: "Vibrato modulates pitch up and down at a steady rate. Unlike chorus, there's no dry signal mixed in — the whole sound wobbles.",
    how: "A short delay's time is modulated by an LFO. As the delay grows or shrinks, the pitch falls or rises (Doppler-style).",
    factory: makeVibrato,
    params: [
      { kind: "knob", id: "rate", label: "RATE", min: 0.5, max: 12, step: 0.1, default: 5, unit: "Hz", explain: "Wobble speed." },
      { kind: "knob", id: "depth", label: "DEPTH", min: 0.5, max: 10, step: 0.1, default: 4, unit: "ms", explain: "Wobble size." },
    ],
    presets: [
      { name: "★ SEASICK", values: { rate: 7, depth: 9 } },
      { name: "VOCAL VIBRATO", values: { rate: 5, depth: 2 } },
      { name: "SUBTLE", values: { rate: 4, depth: 1 } },
    ],
    listenFor: ["Use sparingly on synths — too much = nausea."],
    signalFlow: "SRC → MOD-DELAY (LFO) → OUT",
    commonMistakes: ["Confusing vibrato (pitch) with tremolo (volume)"],
    related: { devices: ["chorus"] },
    source: "Live 12 manual §22.36",
  },
  {
    slug: "echo",
    defaultSample: "vox-chop",
    name: "Echo",
    category: "TIME",
    tagline: "Modern stereo delay with character.",
    what: "Echo is Live's flagship delay: stereo timing, filtering inside the feedback path, and tonal character built in. Think tape, BBD, digital — all in one.",
    how: "Two delays (left + right) with their own times and feedback paths. A high-pass and low-pass shape each repeat. Repeats get darker and dirtier.",
    factory: makeEcho,
    params: [
      { kind: "knob", id: "timeL", label: "TIME L", min: 0.05, max: 1.5, step: 0.005, default: 0.375, unit: "s", explain: "Left echo gap." },
      { kind: "knob", id: "timeR", label: "TIME R", min: 0.05, max: 1.5, step: 0.005, default: 0.5, unit: "s", explain: "Right echo gap (offset = wide)." },
      { kind: "knob", id: "feedback", label: "FEEDBACK", min: 0, max: 0.9, step: 0.01, default: 0.45, explain: "How many repeats." },
      { kind: "knob", id: "hp", label: "HIGH PASS", min: 20, max: 1000, step: 5, default: 200, unit: "Hz", explain: "Cuts low end from each echo." },
      { kind: "knob", id: "lp", label: "LOW PASS", min: 1000, max: 16000, step: 50, default: 6000, unit: "Hz", explain: "Darkens each echo." },
      { kind: "knob", id: "wet", label: "WET", min: 0, max: 1, step: 0.01, default: 0.6, explain: "Echo level." },
    ],
    presets: [
      { name: "★ DUB STEREO", values: { timeL: 0.375, timeR: 0.5, feedback: 0.78, hp: 250, lp: 2000, wet: 0.8 } },
      { name: "SLAP STEREO", values: { timeL: 0.09, timeR: 0.13, feedback: 0.1, hp: 200, lp: 8000, wet: 0.4 } },
      { name: "PING PONG", values: { timeL: 0.25, timeR: 0.5, feedback: 0.55, hp: 200, lp: 5000, wet: 0.55 } },
    ],
    listenFor: ["Different L/R times = wide stereo image.", "HP at 200 keeps echoes from muddying the low end."],
    signalFlow: "SRC → SPLIT → DELAY L/R (FB) → HP → LP → MIX → OUT",
    commonMistakes: ["Same L/R time — kills stereo benefit"],
    related: { devices: ["delay"] },
    source: "Live 12 manual §22.17",
  },
  {
    slug: "grain-delay",
    defaultSample: "vox-chop",
    name: "Grain Delay",
    category: "TIME",
    tagline: "Granular, glitchy, off-rails.",
    what: "Grain Delay chops the input into tiny grains, sprays them through a feedback line, and modulates timing — creating glitchy, pitch-wobbly textures.",
    how: "A delay's time is modulated very fast. Combined with feedback, this generates short bursts (grains) at varying pitches.",
    factory: makeGrainDelay,
    params: [
      { kind: "knob", id: "time", label: "TIME", min: 0.05, max: 1.5, step: 0.005, default: 0.3, unit: "s", explain: "Base delay length." },
      { kind: "knob", id: "rate", label: "RATE", min: 0.5, max: 30, step: 0.5, default: 8, unit: "Hz", explain: "Spray rate (grain density)." },
      { kind: "knob", id: "spray", label: "SPRAY", min: 0, max: 30, step: 0.5, default: 5, explain: "Pitch & timing chaos." },
      { kind: "knob", id: "feedback", label: "FEEDBACK", min: 0, max: 0.95, step: 0.01, default: 0.5, explain: "Repeats." },
      { kind: "knob", id: "wet", label: "WET", min: 0, max: 1, step: 0.01, default: 0.6, explain: "Mix." },
    ],
    presets: [
      { name: "★ GLITCH WALL", values: { time: 0.5, rate: 20, spray: 25, feedback: 0.85, wet: 1 } },
      { name: "STUTTER", values: { time: 0.12, rate: 12, spray: 3, feedback: 0.5, wet: 0.55 } },
    ],
    listenFor: ["High spray on vocals = otherworldly fragments."],
    signalFlow: "SRC → MOD-DELAY (fast LFO) ⟲ FB → MIX → OUT",
    commonMistakes: ["Feedback too high = endless wash"],
    source: "Live 12 manual §22.20",
  },
  {
    slug: "filter-delay",
    defaultSample: "drum-loop",
    name: "Filter Delay",
    category: "TIME",
    tagline: "Three independent band-passed echoes.",
    what: "Filter Delay splits the input into three bands and gives each its own delay time and feedback. Lows can echo at quarter notes while highs ping at sixteenths.",
    how: "Three parallel band-pass filters feed three independent delays. Each delay has its own feedback path.",
    factory: makeFilterDelay,
    params: [
      { kind: "knob", id: "lt", label: "LOW TIME", min: 0.05, max: 1.5, step: 0.005, default: 0.5, unit: "s", explain: "Low-band delay." },
      { kind: "knob", id: "lfb", label: "LOW FB", min: 0, max: 0.95, step: 0.01, default: 0.4, explain: "Low repeats." },
      { kind: "knob", id: "mt", label: "MID TIME", min: 0.05, max: 1.5, step: 0.005, default: 0.375, unit: "s", explain: "Mid delay." },
      { kind: "knob", id: "mfb", label: "MID FB", min: 0, max: 0.95, step: 0.01, default: 0.4, explain: "Mid repeats." },
      { kind: "knob", id: "ht", label: "HI TIME", min: 0.05, max: 1.5, step: 0.005, default: 0.25, unit: "s", explain: "High delay." },
      { kind: "knob", id: "hfb", label: "HI FB", min: 0, max: 0.95, step: 0.01, default: 0.4, explain: "High repeats." },
      { kind: "knob", id: "wet", label: "WET", min: 0, max: 1, step: 0.01, default: 0.7, explain: "Mix." },
    ],
    presets: [
      { name: "★ POLYRHYTHM", values: { lt: 0.5, lfb: 0.55, mt: 0.333, mfb: 0.5, ht: 0.166, hfb: 0.5, wet: 0.85 } },
      { name: "SPACED OUT", values: { lt: 0.75, lfb: 0.7, mt: 0.5, mfb: 0.5, ht: 0.25, hfb: 0.6, wet: 0.7 } },
    ],
    listenFor: ["Each band echoing at a different rate creates motion across the spectrum."],
    signalFlow: "SRC → BP×3 → DELAY×3 (FB) → MIX → OUT",
    source: "Live 12 manual §22.19",
  },
  {
    slug: "drum-buss",
    defaultSample: "drum-loop",
    name: "Drum Buss",
    category: "DYNAMICS",
    tagline: "One device for the whole drum bus.",
    what: "Drum Buss is a one-stop processor for drums: high-pass clean-up, drive for character, compression for glue, and a low-shelf 'boom' boost.",
    how: "Signal flow: HP cleans rumble → soft saturator adds character → compressor controls peaks → low shelf adds weight.",
    factory: makeDrumBuss,
    params: [
      { kind: "knob", id: "hp", label: "HP", min: 20, max: 200, step: 1, default: 30, unit: "Hz", explain: "Cuts sub-rumble before drive." },
      { kind: "knob", id: "drive", label: "DRIVE", min: 0, max: 1, step: 0.01, default: 0.2, explain: "Adds character." },
      { kind: "knob", id: "comp", label: "COMP THRES", min: -30, max: 0, step: 0.5, default: -14, unit: "dB", explain: "Lower = more squash." },
      { kind: "knob", id: "boom", label: "BOOM", min: 0, max: 12, step: 0.5, default: 3, unit: "dB", explain: "Sub-bass weight." },
    ],
    presets: [
      { name: "★ TRAP", values: { hp: 25, drive: 0.45, comp: -18, boom: 8 } },
      { name: "ROCK BUS", values: { hp: 40, drive: 0.35, comp: -16, boom: 2 } },
      { name: "TIGHT BUS", values: { hp: 60, drive: 0.1, comp: -10, boom: 0 } },
    ],
    listenFor: ["A little drive transforms the room sound into something cohesive.", "Boom is mono-friendly weight, not muddiness."],
    signalFlow: "DRUMS → HP → DRIVE → COMP → BOOM SHELF → OUT",
    commonMistakes: ["Boom too high → flubby", "Drive too high on already-loud drums → distortion"],
    related: { devices: ["compressor", "saturator", "glue-compressor"] },
    source: "Live 12 manual §22.15",
  },
  {
    slug: "auto-pan",
    defaultSample: "chord-pad",
    name: "Auto Pan",
    category: "MOD",
    tagline: "LFO-driven panning & tremolo.",
    what: "Auto Pan rocks the sound between left and right (or up and down in level) with an LFO. Use it as stereo motion, rhythmic tremolo, or mono volume pulse.",
    how: "An LFO modulates the gain of the left and right channels in opposite directions. Same LFO on both = tremolo (volume); opposite = panning.",
    factory: makeAutoPan,
    params: [
      { kind: "knob", id: "rate", label: "RATE", min: 0.05, max: 12, step: 0.05, default: 1, unit: "Hz", explain: "Pan speed." },
      { kind: "knob", id: "amount", label: "AMOUNT", min: 0, max: 0.5, step: 0.01, default: 0.4, explain: "How wide the pan." },
    ],
    presets: [
      { name: "★ HARD PAN", values: { rate: 4, amount: 0.5 } },
      { name: "LAZY MOTION", values: { rate: 0.25, amount: 0.3 } },
      { name: "TREMOLO 8th", values: { rate: 5, amount: 0.45 } },
    ],
    listenFor: ["Headphones reveal the panning best.", "Slow rate + small amount adds movement to a static pad."],
    signalFlow: "SRC → L-GAIN(LFO) + R-GAIN(-LFO) → MERGE → OUT",
    source: "Live 12 manual §22.5",
  },
  {
    slug: "freq-shifter",
    defaultSample: "vox-chop",
    name: "Frequency Shifter",
    category: "MOD",
    tagline: "Linear pitch shift — bell tones & chaos.",
    what: "Unlike a pitch shifter (which keeps musical intervals), a frequency shifter slides every frequency by the same amount. Result: inharmonic, metallic, alien.",
    how: "Approximated here as ring modulation (multiply by a sine). Real Live 12 uses a Hilbert transform; the audible character is similar at small offsets.",
    factory: makeFreqShift,
    params: [
      { kind: "knob", id: "shift", label: "SHIFT", min: 0.5, max: 1500, step: 0.5, default: 100, unit: "Hz", explain: "How far frequencies move." },
      { kind: "knob", id: "wet", label: "WET", min: 0, max: 1, step: 0.01, default: 1, explain: "Mix." },
    ],
    presets: [
      { name: "★ ALIEN", values: { shift: 800, wet: 1 } },
      { name: "BELL TONES", values: { shift: 30, wet: 1 } },
      { name: "CHIRP", values: { shift: 200, wet: 0.6 } },
    ],
    listenFor: ["Tiny shifts (5–20 Hz) sound like a chorus from another planet.", "Big shifts on drums = robot percussion."],
    signalFlow: "SRC × SINE(shift Hz) → OUT  (ring-mod approximation)",
    commonMistakes: ["Confusing with pitch shifter — this destroys harmonic relationships on purpose"],
    source: "Live 12 manual §22.21",
  },
];

export const deviceBySlug = (s: string) => DEVICES.find((d) => d.slug === s);
