import type { Mission } from "./types";

const w1: Mission[] = [
  {
    slug: "what-is-live",
    world: "first-contact",
    number: 1,
    title: "What Is Live?",
    tagline: "A DAW with two brains.",
    xp: 50,
    badge: { slug: "first-boot", name: "First Boot" },
    explainer: [
      { kind: "lead", text: "Ableton Live is a Digital Audio Workstation built around two complementary views: Session for non-linear jamming, Arrangement for linear composition." },
      { kind: "para", text: "Where most DAWs only give you a timeline, Live also gives you a grid of clips you can launch in any order. That single idea is why producers, performers, and sound designers all live inside it." },
      { kind: "list", items: [
        "Session View — clip grid, perfect for ideas, loops, live sets.",
        "Arrangement View — timeline, perfect for full songs.",
        "Devices — instruments and effects, all built in.",
        "Browser — your library of sounds, presets and projects.",
      ]},
      { kind: "callout", tone: "key", text: "Almost everything in Live is non-destructive. You can warp, reverse, slice, and the original sample stays intact." },
    ],
    sim: { type: "interface-tour" },
    quiz: [
      { q: "Live's two main views are…", options: ["Mix & Edit", "Session & Arrangement", "Track & Master", "Studio & Live"], answer: 1 },
      { q: "Session View is best for…", options: ["Linear songs", "Mastering", "Non-linear loop launching", "Video scoring"], answer: 2 },
      { q: "Audio editing in Live is…", options: ["Destructive", "Non-destructive", "Read-only", "MIDI-only"], answer: 1 },
    ],
  },
  {
    slug: "interface-tour",
    world: "first-contact",
    number: 2,
    title: "Interface Tour",
    tagline: "Every panel, named.",
    xp: 60,
    badge: { slug: "cartographer", name: "Cartographer" },
    explainer: [
      { kind: "lead", text: "Click the hotspots to learn each region of Live's window." },
      { kind: "list", items: [
        "Control Bar — tempo, transport, metronome, quantization.",
        "Browser — left sidebar with sounds, samples, packs.",
        "Main View — Session grid or Arrangement timeline.",
        "Detail View — clip & device editor, opens at the bottom.",
        "Info View — hover anything, read what it does.",
      ]},
      { kind: "callout", tone: "tip", text: "Tab toggles between Session and Arrangement. Memorize this immediately." },
    ],
    sim: { type: "interface-tour" },
    quiz: [
      { q: "What key toggles Session/Arrangement?", options: ["Spacebar", "Tab", "Enter", "Shift"], answer: 1 },
      { q: "Tempo lives in the…", options: ["Browser", "Detail View", "Control Bar", "Mixer"], answer: 2 },
      { q: "Where do you edit a clip's notes?", options: ["Control Bar", "Browser", "Detail View", "Info View"], answer: 2 },
    ],
  },
  {
    slug: "browser",
    world: "first-contact",
    number: 3,
    title: "The Browser",
    tagline: "Your library, organised.",
    xp: 50,
    explainer: [
      { kind: "lead", text: "The Browser is where you find sounds, samples, presets and projects. Master it and you'll make tracks twice as fast." },
      { kind: "list", items: [
        "Sounds — instrument presets you can drag onto tracks.",
        "Drums — drum kits and one-shots.",
        "Samples — your own audio files.",
        "Packs — Ableton's official sound libraries.",
        "Categories — Live's tagging system (since Live 12).",
      ]},
      { kind: "callout", tone: "key", text: "Live 12 added Sound Similarity Search — pick a sample and Live finds others that sound like it." },
    ],
    sim: { type: "browser-tour" },
    quiz: [
      { q: "Live 12's Similarity Search finds samples by…", options: ["File name", "Sound", "Date", "Size"], answer: 1 },
      { q: "Drag-and-drop from the Browser to…", options: ["A track", "Only Session", "Only Arrangement", "The Control Bar"], answer: 0 },
      { q: "Categories were added in…", options: ["Live 9", "Live 10", "Live 11", "Live 12"], answer: 3 },
    ],
  },
  {
    slug: "preferences",
    world: "first-contact",
    number: 4,
    title: "Preferences",
    tagline: "Set it up once, properly.",
    xp: 40,
    explainer: [
      { kind: "lead", text: "Open Preferences (Cmd/Ctrl + ,) and configure your audio interface, buffer size, MIDI ports, and file locations before you do anything else." },
      { kind: "list", items: [
        "Audio — driver, sample rate, buffer size (lower = less latency, more CPU).",
        "Link/Tempo/MIDI — controllers and Ableton Link.",
        "File/Folder — auto-save, plugin folders, max undo.",
        "Library — where Packs install.",
        "Theme — light, dark, high-contrast.",
      ]},
      { kind: "callout", tone: "warn", text: "Buffer too low → audio glitches. Too high → noticeable input latency. 256 samples is a safe default for most." },
    ],
    sim: { type: "knob-trainer", preset: { mode: "buffer" } },
    quiz: [
      { q: "Lower buffer size means…", options: ["More latency", "Less latency, more CPU", "Less CPU", "Better quality"], answer: 1 },
      { q: "Open Preferences with…", options: ["Cmd/Ctrl + ,", "Cmd/Ctrl + P", "F5", "Tab"], answer: 0 },
      { q: "Where do plugins get scanned?", options: ["Audio tab", "File/Folder + Plug-Ins tab", "Theme tab", "Library tab"], answer: 1 },
    ],
  },
  {
    slug: "files-projects",
    world: "first-contact",
    number: 5,
    title: "Files & Projects",
    tagline: "How Live saves your work.",
    xp: 40,
    explainer: [
      { kind: "lead", text: "A Live Set is a .als file. A Project is the folder around it that holds samples, recordings and presets." },
      { kind: "list", items: [
        "Always 'Collect All and Save' before sharing a project.",
        "Live Pack (.alp) bundles a project for distribution.",
        "Auto-save runs in the background — turn it on.",
        "Export Audio/Video renders your finished track.",
      ]},
      { kind: "callout", tone: "tip", text: "Name tracks and clips as you work. Future-you will thank present-you." },
    ],
    sim: { type: "none" },
    quiz: [
      { q: "A Live Set extension is…", options: [".alp", ".als", ".adv", ".asd"], answer: 1 },
      { q: "To bundle a project for a friend, use…", options: ["Save As", "Collect All and Save", "Export Audio", "Freeze Track"], answer: 1 },
      { q: ".alp files are…", options: ["Live Sets", "Live Packs", "Audio", "Presets"], answer: 1 },
    ],
  },
];

const w2: Mission[] = [
  {
    slug: "session-view",
    world: "two-views",
    number: 6,
    title: "Session View",
    tagline: "The clip grid.",
    xp: 70,
    badge: { slug: "scene-stealer", name: "Scene Stealer" },
    explainer: [
      { kind: "lead", text: "Session View is a grid: tracks (vertical) and scenes (horizontal). Each cell is a clip slot. Launch clips and scenes to build ideas live." },
      { kind: "list", items: [
        "Click a clip to launch it.",
        "Click a Scene Launch button to fire a whole row.",
        "Stop button kills clips on a track.",
        "Quantize controls when clips actually start.",
      ]},
      { kind: "callout", tone: "key", text: "Set Global Quantize to 1 Bar — clips will sync musically no matter when you click." },
    ],
    sim: { type: "session-grid" },
    quiz: [
      { q: "A scene is…", options: ["A column of clips", "A row of clips", "A single clip", "A track"], answer: 1 },
      { q: "Global Quantize 1 Bar means clips start…", options: ["Immediately", "On next bar", "On next beat", "Never"], answer: 1 },
      { q: "Each track plays…", options: ["All clips at once", "One clip at a time", "Two clips", "Whatever you select"], answer: 1 },
    ],
  },
  {
    slug: "arrangement-view",
    world: "two-views",
    number: 7,
    title: "Arrangement View",
    tagline: "The timeline.",
    xp: 70,
    explainer: [
      { kind: "lead", text: "Arrangement is a horizontal timeline. Tracks stack down. Clips are blocks you can move, resize, split and loop." },
      { kind: "list", items: [
        "Press Tab to switch from Session.",
        "Record Arm + Record captures Session performances into Arrangement.",
        "The Loop Brace repeats a section.",
        "Locators bookmark sections (Intro, Verse, Drop).",
      ]},
    ],
    sim: { type: "arrangement" },
    quiz: [
      { q: "Locators are…", options: ["Loop markers", "Section bookmarks", "Automation points", "Clips"], answer: 1 },
      { q: "Recording Session into Arrangement happens when…", options: ["You press Save", "You hit global Record", "You export", "Always automatic"], answer: 1 },
      { q: "Arrangement clips can be…", options: ["Moved & resized", "Only moved", "Only resized", "Neither"], answer: 0 },
    ],
  },
  {
    slug: "clips",
    world: "two-views",
    number: 8,
    title: "Clips 101 — MIDI vs Audio",
    tagline: "Two clip types. Wildly different powers.",
    xp: 70,
    explainer: [
      { kind: "lead", text: "A clip is a piece of musical content that lives on a track. There are exactly two kinds, and the difference shapes everything you do in Live." },
      { kind: "para", text: "A MIDI clip stores instructions: 'play C4 at velocity 100 for half a beat'. The track's instrument creates the actual sound at playback. You can change the instrument, transpose every note, slow it down, or rewrite the melody — all without losing fidelity, because nothing has been rendered yet." },
      { kind: "para", text: "An audio clip stores a recorded waveform — a long list of amplitude samples (44,100 numbers per second at CD quality). The pitch and timing are baked into the file. You can still transpose, stretch and warp it, but those are processes that re-interpret the existing samples — push them too far and you'll hear artefacts." },
      { kind: "callout", tone: "key", text: "Rule of thumb: write with MIDI, capture performance with audio. MIDI for ideas you'll keep changing; audio when the sound itself is the point (vocals, recorded instruments, sampled loops)." },
      { kind: "list", items: [
        "MIDI clip → notes + velocity + length, edited in the Piano Roll.",
        "Audio clip → waveform + warp markers, edited in the Sample editor.",
        "Both can loop, both can hold automation envelopes.",
        "Drag audio to a MIDI track → Live wraps it in a Simpler so you can play it like an instrument.",
      ]},
      { kind: "callout", tone: "tip", text: "In the simulator below: change the MIDI instrument and the same melody becomes a saw bass, a sine pad, or a square lead instantly. Try the same on the audio clip — you can only stretch and detune the recording you have." },
      { kind: "link", to: "mission", slug: "midi-piano-roll", label: "Next up: edit MIDI in the Piano Roll" },
      { kind: "link", to: "mission", slug: "warping", label: "Audio clips deep-dive: Warping" },
    ],
    sim: { type: "midi-vs-audio" },
    quiz: [
      { q: "MIDI clips contain…", options: ["Audio samples", "Note instructions (pitch, velocity, length)", "Both equally", "Plugin chains"], answer: 1, explain: "MIDI is a list of instructions; the instrument on the track turns it into sound." },
      { q: "Why is MIDI editable forever?", options: ["It's compressed", "Nothing is rendered until playback", "It's smaller", "Live caches it"], answer: 1 },
      { q: "Audio clip transpose is…", options: ["Free, lossless", "A re-pitch process — extreme values cause artefacts", "Impossible", "MIDI-only"], answer: 1 },
    ],
  },
  {
    slug: "tracks",
    world: "two-views",
    number: 9,
    title: "Tracks",
    tagline: "Audio. MIDI. Return. Group. Master.",
    xp: 50,
    explainer: [
      { kind: "list", items: [
        "Audio Track — records & plays audio.",
        "MIDI Track — holds MIDI clips, hosts an instrument.",
        "Return Track — destination for sends (reverb, delay).",
        "Group Track — folder for routing many tracks together.",
        "Master Track — the final output.",
      ]},
    ],
    sim: { type: "mixer" },
    quiz: [
      { q: "Reverb sends go to a…", options: ["Group", "Return", "Master", "MIDI"], answer: 1 },
      { q: "An instrument lives on a…", options: ["Audio", "MIDI", "Return", "Master"], answer: 1 },
      { q: "Group tracks are like…", options: ["Folders", "Plugins", "Sends", "Clips"], answer: 0 },
    ],
  },
  {
    slug: "scenes-follow",
    world: "two-views",
    number: 10,
    title: "Scenes & Follow Actions",
    tagline: "Make clips play themselves.",
    xp: 70,
    badge: { slug: "auto-pilot", name: "Auto Pilot" },
    explainer: [
      { kind: "lead", text: "A scene fires a whole row. Follow Actions tell each clip what to do when it ends — jump to next, loop, play random." },
      { kind: "list", items: [
        "Set scene tempo & time signature for live sets.",
        "Follow Actions: Stop, Play Again, Previous, Next, First, Last, Any, Other.",
        "Live 11+ added linked Follow Action chances per row.",
      ]},
    ],
    sim: { type: "session-grid", preset: { followActions: true } },
    quiz: [
      { q: "Follow Actions trigger…", options: ["When a clip ends", "When you click", "On bar 1", "On record"], answer: 0 },
      { q: "Scenes can override…", options: ["Tempo", "Sample rate", "Buffer", "Theme"], answer: 0 },
      { q: "Which is NOT a Follow Action?", options: ["Next", "Other", "Reverse", "Stop"], answer: 2 },
    ],
  },
];

const w3: Mission[] = [
  {
    slug: "midi-piano-roll",
    world: "midi-audio",
    number: 11,
    title: "MIDI Piano Roll",
    tagline: "Click. Drag. Compose.",
    xp: 80,
    badge: { slug: "note-ninja", name: "Note Ninja" },
    explainer: [
      { kind: "lead", text: "Double-click a MIDI clip to open the piano roll. Pencil mode draws notes; default mode selects them." },
      { kind: "list", items: [
        "B toggles Pencil Mode.",
        "Velocity = how hard a note is hit.",
        "Quantize aligns notes to the grid.",
        "Live 12 added Generative MIDI tools: Stacks, Rhythm, Shape, Seed.",
      ]},
      { kind: "callout", tone: "key", text: "Hold Shift to constrain note movement. Hold Cmd/Ctrl while drawing for finer pitch increments." },
    ],
    sim: { type: "piano-roll" },
    quiz: [
      { q: "B toggles…", options: ["Browser", "Pencil mode", "Bar count", "Bypass"], answer: 1 },
      { q: "Velocity controls…", options: ["Pitch", "Length", "How hard", "Quantize"], answer: 2 },
      { q: "Live 12 generative MIDI is in…", options: ["Mixer", "Browser", "Note transformations", "Master"], answer: 2 },
    ],
  },
  {
    slug: "audio-clips",
    world: "midi-audio",
    number: 12,
    title: "Audio Clips",
    tagline: "Samples that bend to your will.",
    xp: 60,
    explainer: [
      { kind: "lead", text: "Audio clips reference a sample file. They can be transposed, reversed, looped, sliced, and warped — all without touching the original." },
      { kind: "list", items: [
        "Transpose pitch in semitones (-48 to +48).",
        "Detune in cents.",
        "Reverse, Crop, Consolidate.",
        "Set warp markers to align beats.",
      ]},
    ],
    sim: { type: "warp-lab" },
    quiz: [
      { q: "Editing an audio clip is…", options: ["Destructive", "Non-destructive", "Disabled", "MIDI-only"], answer: 1 },
      { q: "Transpose unit is…", options: ["Hz", "Cents", "Semitones", "Bars"], answer: 2 },
      { q: "Detune unit is…", options: ["Hz", "Cents", "Semitones", "Bars"], answer: 1 },
    ],
  },
  {
    slug: "warping",
    world: "midi-audio",
    number: 13,
    title: "Warping",
    tagline: "Lock any sample to your tempo.",
    xp: 90,
    badge: { slug: "warp-wizard", name: "Warp Wizard" },
    explainer: [
      { kind: "lead", text: "Warping stretches audio in time without changing its pitch. Place warp markers on transients, set a Warp Mode, and the clip follows your project tempo." },
      { kind: "list", items: [
        "Beats — drums and percussive material.",
        "Tones — melodic mono material.",
        "Texture — pads, ambience.",
        "Re-Pitch — old-school speed up/down (pitch follows).",
        "Complex / Complex Pro — full mixes (CPU heavy).",
      ]},
      { kind: "callout", tone: "tip", text: "Drag a transient to set a warp marker. Right-click → Warp From Here (Straight) for a quick lock to grid." },
    ],
    sim: { type: "warp-lab" },
    quiz: [
      { q: "Best mode for full mixes?", options: ["Beats", "Tones", "Re-Pitch", "Complex Pro"], answer: 3 },
      { q: "Warping changes…", options: ["Pitch only", "Time without pitch", "Both equally", "Volume"], answer: 1 },
      { q: "Re-Pitch behaves like…", options: ["A vocoder", "A tape machine", "A reverb", "A limiter"], answer: 1 },
    ],
  },
  {
    slug: "recording-audio",
    world: "midi-audio",
    number: 14,
    title: "Recording Audio",
    tagline: "Get sound in.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Set the track input (Ext. In 1, etc.).",
        "Arm the track (red circle).",
        "Hit Record. Live records into the focused view.",
        "Monitor: In, Auto, Off.",
      ]},
      { kind: "callout", tone: "warn", text: "Always check input level — peak around -12 to -6 dB, never clip into the red." },
    ],
    sim: { type: "mixer", preset: { record: true } },
    quiz: [
      { q: "Arm a track to…", options: ["Solo it", "Record it", "Mute it", "Group it"], answer: 1 },
      { q: "Monitor 'Auto' means…", options: ["Always on", "Always off", "On while armed & not playing back", "Off while armed"], answer: 2 },
      { q: "Healthy input level is around…", options: ["0 dB", "-12 to -6 dB", "+6 dB", "-40 dB"], answer: 1 },
    ],
  },
  {
    slug: "comping",
    world: "midi-audio",
    number: 15,
    title: "Comping",
    tagline: "Stitch the perfect take.",
    xp: 70,
    explainer: [
      { kind: "lead", text: "Take Lanes (Live 11+) let you record multiple passes onto a track and assemble the best moments into one comp." },
      { kind: "list", items: [
        "Right-click a track header → Show Take Lanes.",
        "Each loop pass becomes a new lane.",
        "Click any segment to promote it to the master comp.",
        "Works for both audio and MIDI.",
      ]},
    ],
    sim: { type: "arrangement", preset: { takes: true } },
    quiz: [
      { q: "Take Lanes were added in…", options: ["Live 9", "Live 10", "Live 11", "Live 12"], answer: 2 },
      { q: "Comping works on…", options: ["Audio only", "MIDI only", "Both", "Returns"], answer: 2 },
      { q: "Each loop pass becomes…", options: ["A scene", "A take lane", "A device", "A locator"], answer: 1 },
    ],
  },
  {
    slug: "slicing",
    world: "midi-audio",
    number: 16,
    title: "Slicing to MIDI",
    tagline: "Turn any loop into a playable kit.",
    xp: 70,
    explainer: [
      { kind: "lead", text: "Right-click any audio clip → Slice to New MIDI Track. Live chops it on transients (or grid) and loads each slice into a Drum Rack pad." },
      { kind: "list", items: [
        "Slice by warp markers, beats, or transients.",
        "Each slice maps to a MIDI note.",
        "Re-trigger, re-order, glitch — instant remix.",
      ]},
    ],
    sim: { type: "drum-pad", preset: { sliced: true } },
    quiz: [
      { q: "Slicing produces a…", options: ["Sampler", "Drum Rack", "Wavetable", "Operator"], answer: 1 },
      { q: "You can slice by…", options: ["Transients only", "Beats only", "Transients, beats, or warp markers", "Bars only"], answer: 2 },
      { q: "Each slice is triggered by…", options: ["A scene", "A MIDI note", "A macro", "A send"], answer: 1 },
    ],
  },
];

const w4: Mission[] = [
  {
    slug: "instruments-overview",
    world: "devices",
    number: 17,
    title: "Instruments Overview",
    tagline: "Your built-in synths.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Operator — FM synth, deep & metallic.",
        "Wavetable — modern wavetable, the workhorse.",
        "Drift — analog-style mono/poly synth (Live 11+).",
        "Sampler / Simpler — play your own audio as instruments.",
        "Drum Rack — kit container.",
        "Meld (Live 12) — MPE-first dual-engine synth.",
      ]},
    ],
    sim: { type: "knob-trainer", preset: { synth: "wavetable" } },
    quiz: [
      { q: "Meld is what kind of synth?", options: ["FM", "Subtractive", "MPE dual-engine", "Granular"], answer: 2 },
      { q: "Operator uses…", options: ["Subtractive", "FM", "Wavetable", "Granular"], answer: 1 },
      { q: "Drift was added in…", options: ["Live 9", "Live 10", "Live 11", "Live 12"], answer: 2 },
    ],
  },
  {
    slug: "drum-rack",
    world: "devices",
    number: 18,
    title: "Drum Rack",
    tagline: "16 pads, infinite kits.",
    xp: 70,
    badge: { slug: "kit-builder", name: "Kit Builder" },
    explainer: [
      { kind: "lead", text: "Drum Rack is a container — each pad hosts a Simpler (or any device chain) on its own MIDI note." },
      { kind: "list", items: [
        "Drag samples onto pads.",
        "Each pad has its own chain, mixer, sends.",
        "Choke groups silence other pads (hi-hats).",
        "Right-click pad → Browse for replacements.",
      ]},
    ],
    sim: { type: "drum-pad" },
    quiz: [
      { q: "Choke groups are useful for…", options: ["Reverb", "Hi-hats", "Bass", "Master"], answer: 1 },
      { q: "Each pad hosts…", options: ["A track", "A chain (often a Simpler)", "A scene", "A clip"], answer: 1 },
      { q: "Drum Rack pads map to…", options: ["Audio inputs", "MIDI notes", "Sends", "Macros"], answer: 1 },
    ],
  },
  {
    slug: "wavetable",
    world: "devices",
    number: 19,
    title: "Wavetable",
    tagline: "Modern synthesis, made friendly.",
    xp: 70,
    explainer: [
      { kind: "list", items: [
        "Two oscillators scan through wavetables.",
        "Sub osc, noise, two filters, two envelopes, two LFOs.",
        "Modulation matrix at the bottom — drag any source to any destination.",
        "Unison modes for huge stacks.",
      ]},
    ],
    sim: { type: "knob-trainer", preset: { synth: "wavetable" } },
    quiz: [
      { q: "Wavetable's mod matrix is at the…", options: ["Top", "Bottom", "Side", "Hidden"], answer: 1 },
      { q: "Wavetable has how many oscillators?", options: ["1", "2", "4", "6"], answer: 1 },
      { q: "Unison creates…", options: ["Single voice", "Layered detuned voices", "Reverb", "Distortion"], answer: 1 },
    ],
  },
  {
    slug: "operator",
    world: "devices",
    number: 20,
    title: "Operator",
    tagline: "FM synthesis demystified.",
    xp: 80,
    explainer: [
      { kind: "lead", text: "Operator is a 4-operator FM synth. One operator modulates another's frequency to create rich harmonics." },
      { kind: "list", items: [
        "Pick an algorithm to set how operators connect.",
        "Carriers make sound; modulators shape it.",
        "Higher modulator level = more harmonics.",
        "Coarse/Fine ratio defines the timbre.",
      ]},
    ],
    sim: { type: "knob-trainer", preset: { synth: "operator" } },
    quiz: [
      { q: "Operator has how many operators?", options: ["2", "4", "6", "8"], answer: 1 },
      { q: "Carriers…", options: ["Modulate", "Output sound", "Both", "Neither"], answer: 1 },
      { q: "More modulator level →", options: ["Quieter", "More harmonics", "Less harmonics", "Lower pitch"], answer: 1 },
    ],
  },
  {
    slug: "sampler-simpler",
    world: "devices",
    number: 21,
    title: "Sampler & Simpler",
    tagline: "Play any sound as an instrument.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Simpler — one sample, three modes: Classic, One-Shot, Slice.",
        "Sampler — full multi-sample instrument with zones, key/velocity mapping.",
        "Drag any audio onto a MIDI track to auto-create a Simpler.",
      ]},
    ],
    sim: { type: "drum-pad", preset: { simpler: true } },
    quiz: [
      { q: "Simpler's three modes are…", options: ["Loop, Pad, Drum", "Classic, One-Shot, Slice", "FM, AM, PM", "A, B, C"], answer: 1 },
      { q: "For multi-sampled instruments use…", options: ["Simpler", "Sampler", "Operator", "Drift"], answer: 1 },
      { q: "Drag audio to a MIDI track →", options: ["Sampler", "Simpler", "Operator", "Drum Rack"], answer: 1 },
    ],
  },
  {
    slug: "eq-eight",
    world: "devices",
    number: 22,
    title: "EQ Eight",
    tagline: "Shape every frequency.",
    xp: 70,
    badge: { slug: "frequency-fox", name: "Frequency Fox" },
    explainer: [
      { kind: "lead", text: "EQ Eight gives you 8 bands of parametric EQ, each with multiple filter shapes." },
      { kind: "list", items: [
        "High-pass to remove sub rumble.",
        "Bell to boost or cut a focused band.",
        "Shelves for broad tilts.",
        "Hold Cmd/Ctrl + drag for fine adjustments.",
      ]},
      { kind: "callout", tone: "key", text: "Subtractive EQ before additive: cut what's wrong before boosting what's right." },
    ],
    sim: { type: "device-lab", preset: { device: "eq" } },
    quiz: [
      { q: "EQ Eight has how many bands?", options: ["4", "6", "8", "10"], answer: 2 },
      { q: "Remove sub rumble with a…", options: ["High shelf", "Low shelf", "High-pass", "Notch"], answer: 2 },
      { q: "Subtractive EQ means…", options: ["Boost first", "Cut first", "Only boost", "Only shelf"], answer: 1 },
    ],
  },
  {
    slug: "compressor",
    world: "devices",
    number: 23,
    title: "Compressor",
    tagline: "Tame dynamics. Add punch.",
    xp: 80,
    badge: { slug: "dyna-master", name: "Dyna Master" },
    explainer: [
      { kind: "list", items: [
        "Threshold — level above which compression kicks in.",
        "Ratio — how much it squashes.",
        "Attack — how fast it clamps.",
        "Release — how fast it lets go.",
        "Knee — soft vs hard transition.",
        "Makeup — bring level back up.",
      ]},
      { kind: "callout", tone: "tip", text: "Slower attack = more transient through. Faster attack = more squash." },
    ],
    sim: { type: "device-lab", preset: { device: "compressor" } },
    quiz: [
      { q: "Slower attack lets through more…", options: ["Bass", "Transients", "Reverb", "Pitch"], answer: 1 },
      { q: "Ratio of 4:1 means…", options: ["4 dB in = 1 dB over", "1 dB in = 4 dB over", "No effect", "Limiter"], answer: 0 },
      { q: "Makeup gain compensates for…", options: ["Pitch", "Lost level", "Latency", "Width"], answer: 1 },
    ],
  },
  {
    slug: "reverb-delay",
    world: "devices",
    number: 24,
    title: "Reverb & Delay",
    tagline: "Space and echo.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Reverb — space simulation; size, decay, dry/wet.",
        "Hybrid Reverb (Live 11+) blends convolution with algorithmic.",
        "Delay — echoes synced to tempo.",
        "Echo — analog-flavored delay with character.",
        "Always put reverb/delay on a Return for sharing across tracks.",
      ]},
    ],
    sim: { type: "device-lab", preset: { device: "reverb" } },
    quiz: [
      { q: "Hybrid Reverb arrived in…", options: ["Live 9", "Live 10", "Live 11", "Live 12"], answer: 2 },
      { q: "Reverbs are best placed on…", options: ["Each track", "Master", "Returns", "Group"], answer: 2 },
      { q: "Echo is…", options: ["A reverb", "Analog-flavored delay", "A limiter", "A vocoder"], answer: 1 },
    ],
  },
  {
    slug: "saturator-distortion",
    world: "devices",
    number: 25,
    title: "Saturator & Distortion",
    tagline: "Add grit. Add glue.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Saturator — soft to hard saturation curves.",
        "Drive controls how hard you push the curve.",
        "Pedal, Overdrive, Roar (Live 12) — flavored distortions.",
        "Roar adds multi-band processing & feedback paths.",
      ]},
    ],
    sim: { type: "device-lab", preset: { device: "saturator" } },
    quiz: [
      { q: "Roar was added in…", options: ["Live 10", "Live 11", "Live 12", "Live 13"], answer: 2 },
      { q: "Drive in Saturator controls…", options: ["Pitch", "How hard you hit the curve", "Reverb size", "Pan"], answer: 1 },
      { q: "Roar is a…", options: ["Reverb", "Multi-band distortion", "Compressor", "Synth"], answer: 1 },
    ],
  },
  {
    slug: "midi-effects",
    world: "devices",
    number: 26,
    title: "MIDI Effects",
    tagline: "Process notes before sound.",
    xp: 50,
    explainer: [
      { kind: "list", items: [
        "Arpeggiator — turn chords into runs.",
        "Chord — stack intervals on each note.",
        "Scale — force notes into a scale.",
        "Note Echo — note repeats.",
        "Random / Velocity — humanise or chaos.",
      ]},
    ],
    sim: { type: "piano-roll", preset: { midiFx: true } },
    quiz: [
      { q: "Force notes into a scale with…", options: ["Chord", "Scale", "Random", "Velocity"], answer: 1 },
      { q: "Arpeggiator turns chords into…", options: ["Pads", "Runs", "Reverb", "Bass"], answer: 1 },
      { q: "MIDI effects sit…", options: ["After instrument", "Before instrument", "On Master", "On Return"], answer: 1 },
    ],
  },
  {
    slug: "racks-macros",
    world: "devices",
    number: 27,
    title: "Racks & Macros",
    tagline: "Wrap chains. Map controls.",
    xp: 80,
    badge: { slug: "macro-maxxer", name: "Macro Maxxer" },
    explainer: [
      { kind: "lead", text: "Racks group devices into a single unit. Macros are 16 knobs you map to any parameter inside the rack." },
      { kind: "list", items: [
        "Instrument Rack, Audio Effect Rack, MIDI Effect Rack, Drum Rack.",
        "Chain Selector splits zones across chains.",
        "Macro Variations save & recall macro snapshots.",
        "Right-click a parameter → Map to Macro.",
      ]},
    ],
    sim: { type: "knob-trainer", preset: { macros: true } },
    quiz: [
      { q: "How many macros per rack?", options: ["8", "12", "16", "32"], answer: 2 },
      { q: "Macro Variations are…", options: ["Plugins", "Snapshots of macro values", "Sends", "Scenes"], answer: 1 },
      { q: "Chain Selector splits…", options: ["MIDI notes only", "Velocity, key or chain zones", "Audio only", "Returns"], answer: 1 },
    ],
  },
];

const w5: Mission[] = [
  {
    slug: "the-mixer",
    world: "mixing",
    number: 28,
    title: "The Mixer",
    tagline: "Faders, pans, meters.",
    xp: 70,
    explainer: [
      { kind: "list", items: [
        "Volume fader — track level (don't ride hot).",
        "Pan — stereo placement.",
        "Mute / Solo — isolate or silence.",
        "Cue — pre-listen for DJ-style monitoring.",
        "Crossfader A/B — DJ blend across tracks.",
      ]},
    ],
    sim: { type: "mixer" },
    quiz: [
      { q: "Soloing a track…", options: ["Mutes others", "Mutes it", "Records it", "Groups it"], answer: 0 },
      { q: "Crossfader is for…", options: ["EQ", "DJ-style A/B blend", "Reverb", "Pitch"], answer: 1 },
      { q: "Cue lets you…", options: ["Pre-listen", "Record", "Solo", "Pan"], answer: 0 },
    ],
  },
  {
    slug: "sends-returns",
    world: "mixing",
    number: 29,
    title: "Sends & Returns",
    tagline: "Share effects. Save CPU.",
    xp: 70,
    badge: { slug: "send-it", name: "Send It" },
    explainer: [
      { kind: "lead", text: "Instead of a reverb on every track, put one on a Return and send each track to it. Cleaner, lighter, more cohesive." },
      { kind: "list", items: [
        "Cmd/Ctrl + Alt + T — create Return Track.",
        "Each track gets a Send knob per Return.",
        "Pre/Post toggle: Pre = send before fader, Post = after.",
      ]},
    ],
    sim: { type: "send-return" },
    quiz: [
      { q: "Pre-fader send is independent of…", options: ["Pan", "Volume fader", "Solo", "Mute"], answer: 1 },
      { q: "Returns receive…", options: ["MIDI", "Sends", "Inputs", "Scenes"], answer: 1 },
      { q: "Why use a return reverb?", options: ["Louder", "CPU & cohesion", "Pitch shift", "Quantize"], answer: 1 },
    ],
  },
  {
    slug: "groups-routing",
    world: "mixing",
    number: 30,
    title: "Groups & Routing",
    tagline: "Sub-mixes and signal flow.",
    xp: 80,
    explainer: [
      { kind: "list", items: [
        "Cmd/Ctrl + G groups tracks.",
        "Group is a real audio bus — process it.",
        "Track In/Out lets you route any track anywhere.",
        "Audio From: external input, another track, Resampling.",
      ]},
    ],
    sim: { type: "routing-puzzle", preset: { groups: true } },
    quiz: [
      { q: "Group tracks are…", options: ["Folders only", "Real audio buses", "Returns", "MIDI"], answer: 1 },
      { q: "Resampling sends Master back to…", options: ["A scene", "An audio track input", "A return", "A clip"], answer: 1 },
      { q: "Cmd/Ctrl + G…", options: ["Saves", "Groups", "Quantizes", "Records"], answer: 1 },
    ],
  },
  {
    slug: "automation",
    world: "mixing",
    number: 31,
    title: "Automation",
    tagline: "Make parameters move.",
    xp: 80,
    badge: { slug: "auto-mate", name: "Auto Mate" },
    explainer: [
      { kind: "lead", text: "Automation records parameter changes over time. Press A in Arrangement to show automation lanes; draw or record." },
      { kind: "list", items: [
        "Click any parameter then choose it from the lane menu.",
        "Curves: linear, then drag a midpoint to bend.",
        "Live 11+ added shaped automation curves.",
        "Clip Envelopes hold automation inside a single clip.",
      ]},
    ],
    sim: { type: "arrangement", preset: { automation: true } },
    quiz: [
      { q: "Show automation in Arrangement with…", options: ["B", "A", "S", "M"], answer: 1 },
      { q: "Clip-only automation lives in…", options: ["Mixer", "Clip Envelopes", "Master", "Returns"], answer: 1 },
      { q: "Curved automation arrived in…", options: ["Live 9", "Live 10", "Live 11", "Live 12"], answer: 2 },
    ],
  },
  {
    slug: "modulation-lanes",
    world: "mixing",
    number: 32,
    title: "Modulation Lanes",
    tagline: "Beyond automation.",
    xp: 70,
    explainer: [
      { kind: "lead", text: "Modulation in Live 12 is offset-based — it nudges a parameter relative to its current value, on top of automation." },
      { kind: "list", items: [
        "Arrangement Modulation lanes (Live 12).",
        "Combine with macros and LFOs (Max for Live).",
        "Great for evolving textures.",
      ]},
    ],
    sim: { type: "arrangement", preset: { modulation: true } },
    quiz: [
      { q: "Modulation in Live 12 is…", options: ["Absolute", "Offset-based", "MIDI-only", "Disabled"], answer: 1 },
      { q: "Modulation stacks with…", options: ["Nothing", "Automation", "Sends only", "Solo"], answer: 1 },
      { q: "Modulation lanes appeared in…", options: ["Live 10", "Live 11", "Live 12", "Live 8"], answer: 2 },
    ],
  },
  {
    slug: "sidechain",
    world: "mixing",
    number: 33,
    title: "Sidechain Compression",
    tagline: "The pump.",
    xp: 90,
    badge: { slug: "sidechain-sniper", name: "Sidechain Sniper" },
    explainer: [
      { kind: "lead", text: "Use the kick to duck the bass (or pads). Open the Compressor's Sidechain panel and set the kick track as input." },
      { kind: "list", items: [
        "Threshold sets when the duck starts.",
        "Ratio sets how deep.",
        "Attack & release sculpt the pump shape.",
        "Try fast attack, medium release for classic dance pump.",
      ]},
    ],
    sim: { type: "sidechain" },
    quiz: [
      { q: "Sidechain ducks…", options: ["The kick", "The track being compressed", "The reverb", "Master"], answer: 1 },
      { q: "Classic pump uses…", options: ["Slow attack, slow release", "Fast attack, medium release", "No release", "Soft knee only"], answer: 1 },
      { q: "Sidechain input panel is on the…", options: ["EQ", "Compressor", "Reverb", "Saturator"], answer: 1 },
    ],
  },
  {
    slug: "max-for-live",
    world: "mixing",
    number: 34,
    title: "Max for Live",
    tagline: "Build your own devices.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Max for Live (M4L) is a visual coding env baked into Live Suite.",
        "Hundreds of free devices on maxforlive.com.",
        "Build custom synths, sequencers, MIDI tools.",
        "Convolution Reverb, LFO, Envelope Follower are official M4L devices.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "M4L ships with…", options: ["Intro", "Standard", "Suite", "Lite"], answer: 2 },
      { q: "Envelope Follower is…", options: ["A clip", "An M4L device", "A scene", "A track"], answer: 1 },
      { q: "Max is…", options: ["Audio editor", "Visual programming env", "Mastering tool", "DJ app"], answer: 1 },
    ],
  },
];

const w6: Mission[] = [
  {
    slug: "push-controllers",
    world: "performance",
    number: 35,
    title: "Push & Controllers",
    tagline: "Get hands on.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Push 3 — hardware instrument, can run Live standalone.",
        "Auto-mapping for popular controllers.",
        "User Remote Scripts for custom mapping.",
      ]},
    ],
    sim: { type: "drum-pad", preset: { push: true } },
    quiz: [
      { q: "Push 3 can run…", options: ["Only with computer", "Standalone", "MIDI only", "Audio only"], answer: 1 },
      { q: "Custom mapping uses…", options: ["Macros", "Remote Scripts", "Sends", "Cue"], answer: 1 },
      { q: "Push is…", options: ["A plugin", "Hardware", "A scene", "A clip"], answer: 1 },
    ],
  },
  {
    slug: "midi-mapping",
    world: "performance",
    number: 36,
    title: "MIDI Mapping",
    tagline: "Map any knob to anything.",
    xp: 70,
    badge: { slug: "map-master", name: "Map Master" },
    explainer: [
      { kind: "lead", text: "Cmd/Ctrl + M enters MIDI Map mode. Click a parameter, move a control, done. Set min/max ranges per mapping." },
      { kind: "list", items: [
        "Cmd/Ctrl + K — Key Map mode (laptop keys).",
        "Mappings are per Live Set.",
        "Right-click a mapping to invert range.",
      ]},
    ],
    sim: { type: "midi-map" },
    quiz: [
      { q: "MIDI Map mode shortcut…", options: ["Cmd/Ctrl + M", "Cmd/Ctrl + K", "Cmd/Ctrl + L", "Cmd/Ctrl + J"], answer: 0 },
      { q: "Key Map shortcut…", options: ["Cmd/Ctrl + M", "Cmd/Ctrl + K", "Cmd/Ctrl + L", "Cmd/Ctrl + J"], answer: 1 },
      { q: "Mappings save…", options: ["Globally", "Per Live Set", "Per Pack", "Per scene"], answer: 1 },
    ],
  },
  {
    slug: "tempo-following",
    world: "performance",
    number: 37,
    title: "Tempo Following",
    tagline: "Live follows you.",
    xp: 60,
    explainer: [
      { kind: "lead", text: "Tempo Follower (Live 11+) listens to an audio input (e.g. drummer) and tracks tempo in real time." },
      { kind: "list", items: [
        "Set Audio From in the Tempo Follower preferences.",
        "Engage the Follow button on the tempo display.",
        "Best with strong rhythmic input.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "Tempo Follower added in…", options: ["Live 9", "Live 10", "Live 11", "Live 12"], answer: 2 },
      { q: "It follows…", options: ["MIDI clock", "Audio input", "Scene tempo", "Cue"], answer: 1 },
      { q: "Best input is…", options: ["Pad", "Strong rhythmic source", "Reverb", "Silence"], answer: 1 },
    ],
  },
  {
    slug: "cv-tools",
    world: "performance",
    number: 38,
    title: "CV Tools",
    tagline: "Talk to modular.",
    xp: 50,
    explainer: [
      { kind: "list", items: [
        "CV Instrument & CV Triggers send pitch/gate to Eurorack via DC-coupled interface.",
        "CV In analyses incoming CV.",
        "Use to sequence hardware from MIDI clips.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "CV needs a … interface", options: ["AC-coupled", "DC-coupled", "USB-only", "MIDI-only"], answer: 1 },
      { q: "CV Tools talk to…", options: ["Plugins", "Modular synths", "Push", "Returns"], answer: 1 },
      { q: "CV In…", options: ["Sends CV", "Receives CV", "Sends MIDI", "Records audio"], answer: 1 },
    ],
  },
  {
    slug: "ableton-link",
    world: "performance",
    number: 39,
    title: "Ableton Link",
    tagline: "Sync apps over Wi-Fi.",
    xp: 50,
    explainer: [
      { kind: "lead", text: "Link keeps multiple devices on the same beat over a local network — no cables, no master clock." },
      { kind: "list", items: [
        "Toggle in the Control Bar.",
        "Works with hundreds of apps and hardware.",
        "Each peer can change tempo; everyone follows.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "Link sync uses…", options: ["MIDI cable", "Wi-Fi/LAN", "Audio cable", "USB only"], answer: 1 },
      { q: "Link tempo control is…", options: ["Single master", "Anyone can change", "Locked", "Read-only"], answer: 1 },
      { q: "Link is…", options: ["Paid plugin", "Free, built-in", "Hardware only", "iOS only"], answer: 1 },
    ],
  },
  {
    slug: "exporting",
    world: "performance",
    number: 40,
    title: "Exporting",
    tagline: "Render the final file.",
    xp: 60,
    badge: { slug: "shipped-it", name: "Shipped It" },
    explainer: [
      { kind: "lead", text: "Cmd/Ctrl + Shift + R opens Export Audio/Video. Set the loop brace to define the region first." },
      { kind: "list", items: [
        "Render as Loop renders just the loop.",
        "WAV 24-bit / 44.1 kHz for distribution; 32-bit float for mastering hand-off.",
        "Normalize off — leave headroom.",
        "Render Each Track separately for stems.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "For mastering hand-off use…", options: ["MP3", "WAV 16-bit", "WAV 24-bit / 32-bit float", "FLAC"], answer: 2 },
      { q: "Stems come from…", options: ["Render Master", "Render Each Track", "Render Loop", "Render MIDI"], answer: 1 },
      { q: "Export shortcut…", options: ["Cmd/Ctrl + R", "Cmd/Ctrl + Shift + R", "Cmd/Ctrl + E", "F12"], answer: 1 },
    ],
  },
  {
    slug: "live-sets-projects",
    world: "performance",
    number: 41,
    title: "Live Sets & Projects",
    tagline: "Stay organised.",
    xp: 40,
    explainer: [
      { kind: "list", items: [
        "Project = folder, Set = .als file inside it.",
        "Templates save your default Set.",
        "Bounce in Place freezes a track to audio.",
        "Freeze + Flatten trades CPU for disk.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "Freezing trades…", options: ["RAM for CPU", "CPU for disk", "Disk for RAM", "Quality for size"], answer: 1 },
      { q: "Bounce in Place…", options: ["Renders to audio in place", "Deletes a track", "Exports stems", "Locks tempo"], answer: 0 },
      { q: "Templates set your…", options: ["Default Live Set", "Tempo only", "Theme", "Plugin folder"], answer: 0 },
    ],
  },
  {
    slug: "troubleshooting",
    world: "performance",
    number: 42,
    title: "Troubleshooting",
    tagline: "When things break.",
    xp: 50,
    explainer: [
      { kind: "list", items: [
        "Crackling? Raise buffer size, freeze tracks.",
        "Plugins not showing? Re-scan in Preferences.",
        "Latency issues? Check Driver Error Compensation.",
        "Lost project? Check Auto-Save folder.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "Crackling fix #1…", options: ["Lower buffer", "Raise buffer / freeze", "Add reverb", "Solo"], answer: 1 },
      { q: "Auto-saves are in the…", options: ["Trash", "Project's Backup folder", "Library root", "Master track"], answer: 1 },
      { q: "Plugins missing →", options: ["Re-scan in Preferences", "Reinstall Live", "New project", "Disable MIDI"], answer: 0 },
    ],
  },
];

const wExtra: Mission[] = [
  {
    slug: "capture-midi",
    world: "first-contact",
    number: 43,
    title: "Capture MIDI",
    tagline: "The take you didn't record — recovered.",
    xp: 60,
    badge: { slug: "time-traveller", name: "Time Traveller" },
    explainer: [
      { kind: "lead", text: "Capture MIDI rebuilds the notes you just played even when Record was off. Live keeps a rolling MIDI buffer in the background." },
      { kind: "list", items: [
        "Press the Capture button (camera icon, top-left) any time after playing.",
        "Live drops the captured notes onto the armed MIDI track at the right tempo.",
        "Works in both Session and Arrangement, with or without the metronome.",
      ]},
      { kind: "callout", tone: "key", text: "If you ever say 'wait, that was good' — you almost certainly already have it." },
    ],
    sim: { type: "piano-roll" },
    quiz: [
      { q: "Capture MIDI requires Record to be armed first.", options: ["True", "False"], answer: 1 },
      { q: "What gets captured?", options: ["Audio", "MIDI you just played", "Automation only"], answer: 1 },
      { q: "Where does the captured clip land?", options: ["A new track", "The armed MIDI track", "The Master"], answer: 1 },
    ],
  },
  {
    slug: "take-lanes",
    world: "two-views",
    number: 44,
    title: "Take Lanes & Comping",
    tagline: "Stack takes. Pick the best bits. Make one perfect take.",
    xp: 80,
    badge: { slug: "comp-king", name: "Comp King" },
    explainer: [
      { kind: "lead", text: "Take Lanes (Live 11+) record every pass underneath the main track. You then highlight the best moment from each lane and Live composites them into the final clip." },
      { kind: "list", items: [
        "Right-click a track header → Show Take Lanes.",
        "Loop a section, hit Record — each pass lands on a new lane.",
        "Drag across the parts you like; they appear on the top lane (the comp).",
        "Works for both Audio and MIDI.",
      ]},
      { kind: "callout", tone: "tip", text: "Comping is the secret behind 'how did they sing that perfectly?' — they didn't, in one go." },
    ],
    sim: { type: "arrangement" },
    quiz: [
      { q: "Take Lanes were introduced in…", options: ["Live 9", "Live 10", "Live 11", "Live 12"], answer: 2 },
      { q: "The comp lives on…", options: ["A return", "The main (top) lane", "The Master"], answer: 1 },
      { q: "Take Lanes work for…", options: ["Audio only", "MIDI only", "Audio and MIDI"], answer: 2 },
    ],
  },
  {
    slug: "mpe-tuning",
    world: "midi-audio",
    number: 45,
    title: "MPE & Tuning Systems",
    tagline: "Per-note bends. Microtonal scales. Beyond 12-EDO.",
    xp: 90,
    badge: { slug: "microtonal", name: "Microtonal" },
    explainer: [
      { kind: "lead", text: "MPE (MIDI Polyphonic Expression) lets each note carry its own pitch-bend, slide and pressure. Live 11+ supports it natively across Wavetable, Sampler, Arpeggiator and Drum Rack pads." },
      { kind: "list", items: [
        "Plug in an MPE controller (Push 3, Seaboard, LinnStrument).",
        "Live 12 added Tuning Systems — load a Scala (.scl) file to play in just intonation, 24-EDO, etc.",
        "Tuning is global per Set; every device that supports it follows.",
      ]},
      { kind: "callout", tone: "key", text: "MPE turns MIDI from a piano roll into a string instrument: vibrato, slides, dynamic timbre, all per note." },
    ],
    sim: { type: "piano-roll" },
    quiz: [
      { q: "MPE stands for…", options: ["MIDI Polyphonic Expression", "Multi Patch Editor", "Mod Performance Engine"], answer: 0 },
      { q: "Tuning Systems arrived in…", options: ["Live 10", "Live 11", "Live 12"], answer: 2 },
      { q: "A .scl file is…", options: ["A sample", "A Scala tuning file", "A preset"], answer: 1 },
    ],
  },
  {
    slug: "meld",
    world: "devices",
    number: 46,
    title: "Meld",
    tagline: "Live 12's MPE-first dual-engine synth.",
    xp: 80,
    badge: { slug: "meld-mage", name: "Meld Mage" },
    explainer: [
      { kind: "lead", text: "Meld is a bi-timbral synth designed around MPE. Two independent engines (each with multiple oscillator types) layer or split across the keyboard." },
      { kind: "list", items: [
        "Engines: classic, noise, FM, formant, additive — pick one per voice.",
        "Built-in modulation matrix with macro destinations.",
        "Designed to feel expressive on Push 3 and other MPE controllers.",
      ]},
      { kind: "callout", tone: "tip", text: "Even without an MPE controller, Meld's two-engine layering makes great evolving pads." },
    ],
    sim: { type: "knob-trainer" },
    quiz: [
      { q: "Meld shipped with…", options: ["Live 10", "Live 11", "Live 12"], answer: 2 },
      { q: "How many engines?", options: ["1", "2", "4"], answer: 1 },
      { q: "Meld is designed for…", options: ["MPE expression", "Drum sampling", "Mastering"], answer: 0 },
    ],
  },
  {
    slug: "drum-sampler",
    world: "devices",
    number: 47,
    title: "Drum Sampler",
    tagline: "Modern, multi-sample drum hits with built-in shaping.",
    xp: 70,
    badge: { slug: "kit-builder", name: "Kit Builder" },
    explainer: [
      { kind: "lead", text: "Drum Sampler (Live 12) replaces Simpler on each pad of the new Drum Rack. Multi-sample, velocity layers, pitch envelope, drive — built for one-shot drums, not loops." },
      { kind: "list", items: [
        "Drag a folder of velocity layers — Drum Sampler maps them automatically.",
        "Per-pad pitch envelope, filter, drive, compression in one device.",
        "Round-robin so repeated hits don't sound like a machine gun.",
      ]},
      { kind: "callout", tone: "tip", text: "If you'd been stacking Saturator + EQ + Simpler on every pad — Drum Sampler is that, in one." },
    ],
    sim: { type: "drum-pad" },
    quiz: [
      { q: "Drum Sampler ships with…", options: ["Live 11", "Live 12"], answer: 1 },
      { q: "It replaces…", options: ["Simpler on drum pads", "Operator", "Wavetable"], answer: 0 },
      { q: "Round-robin avoids…", options: ["Machine-gun repeats", "Pitch drift", "Latency"], answer: 0 },
    ],
  },
  {
    slug: "hybrid-reverb",
    world: "devices",
    number: 48,
    title: "Hybrid Reverb",
    tagline: "Convolution + algorithmic, blended in one device.",
    xp: 70,
    badge: { slug: "space-architect", name: "Space Architect" },
    explainer: [
      { kind: "lead", text: "Hybrid Reverb runs a convolution engine (real-space impulse responses) and an algorithmic engine in parallel and lets you crossfade between them." },
      { kind: "list", items: [
        "Convolution side: real halls, plates, springs, custom IRs.",
        "Algorithmic side: Quartz, Shimmer, Tides, Ghost — modern character.",
        "Crossfade them with one knob.",
      ]},
      { kind: "callout", tone: "key", text: "Use convolution for realism, algorithmic for movement — blend for both." },
    ],
    sim: { type: "send-return" },
    quiz: [
      { q: "Hybrid Reverb blends…", options: ["Convolution + algorithmic", "Two delays", "EQ + reverb"], answer: 0 },
      { q: "Convolution uses…", options: ["Recorded impulse responses", "Sine waves", "FM"], answer: 0 },
      { q: "Best place to insert?", options: ["Return track", "Master input", "MIDI clip"], answer: 0 },
    ],
  },
  {
    slug: "roar",
    world: "devices",
    number: 49,
    title: "Roar",
    tagline: "Multiband, modulated saturation. Tonal weapon.",
    xp: 70,
    badge: { slug: "tone-shaper", name: "Tone Shaper" },
    explainer: [
      { kind: "lead", text: "Roar (Live 12) is a multi-stage saturator with up to three bands, multiple distortion algorithms per stage, internal modulators, and a feedback path." },
      { kind: "list", items: [
        "Pick from 13 saturation algorithms (Tube, Diode, Wavefolder, Bit, Digital Clip…).",
        "Run them in series, parallel, or split into 2–3 frequency bands.",
        "Built-in LFO/envelope follower modulates any stage parameter.",
      ]},
      { kind: "callout", tone: "tip", text: "Use the multiband mode to saturate only the highs of a vocal — adds air without crunching the body." },
    ],
    sim: { type: "knob-trainer" },
    quiz: [
      { q: "Roar is a…", options: ["Multiband saturator", "Reverb", "Synth"], answer: 0 },
      { q: "Max bands?", options: ["1", "2", "3"], answer: 2 },
      { q: "Roar shipped in…", options: ["Live 11", "Live 12"], answer: 1 },
    ],
  },
  {
    slug: "glue-compressor",
    world: "mixing",
    number: 50,
    title: "Glue Compressor",
    tagline: "The bus compressor that makes a mix feel like one record.",
    xp: 70,
    badge: { slug: "bus-master", name: "Bus Master" },
    explainer: [
      { kind: "lead", text: "Glue is Live's emulation of the classic SSL G-bus compressor — fast attack, musical release, designed for the master bus or a drum bus." },
      { kind: "list", items: [
        "Threshold low (1–3 dB gain reduction) is enough.",
        "Attack 10ms, Release Auto, Ratio 4 — start there.",
        "Built-in soft clipper at the output.",
      ]},
      { kind: "callout", tone: "key", text: "If your mix sounds like separate tracks, Glue is the cheat code." },
    ],
    sim: { type: "knob-trainer", preset: { device: "compressor" } },
    quiz: [
      { q: "Glue emulates which classic?", options: ["1176", "SSL G-bus", "LA-2A"], answer: 1 },
      { q: "Typical bus GR?", options: ["1–3 dB", "10 dB", "20 dB"], answer: 0 },
      { q: "Output stage has…", options: ["Soft clipper", "Reverb", "Limiter"], answer: 0 },
    ],
  },
  {
    slug: "limiter-truepeak",
    world: "mixing",
    number: 51,
    title: "Limiter & True Peak",
    tagline: "The last device on every master.",
    xp: 70,
    badge: { slug: "loudness", name: "Loudness" },
    explainer: [
      { kind: "lead", text: "Limiter is a brick-wall: nothing crosses the ceiling. Set Ceiling around -1 dBTP to stay safe for streaming codecs." },
      { kind: "list", items: [
        "Gain pushes signal up; Ceiling sets the absolute peak.",
        "Lookahead 3 ms is the safe default; longer = cleaner but more latency.",
        "True Peak option detects inter-sample peaks that show up after MP3/AAC encoding.",
      ]},
      { kind: "callout", tone: "warn", text: "Limiting more than 3–4 dB will pump and squash. Mix into the limiter, don't fix the mix with it." },
    ],
    sim: { type: "knob-trainer", preset: { device: "compressor" } },
    quiz: [
      { q: "A limiter is a…", options: ["Brick-wall compressor", "Reverb", "EQ"], answer: 0 },
      { q: "Streaming-safe ceiling?", options: ["-1 dBTP", "0 dB", "+3 dB"], answer: 0 },
      { q: "True peak prevents…", options: ["Inter-sample clipping", "Pitch drift", "Latency"], answer: 0 },
    ],
  },
  {
    slug: "warp-modes-deep",
    world: "midi-audio",
    number: 52,
    title: "Warp Modes Deep Dive",
    tagline: "Beats, Tones, Texture, Re-Pitch, Complex, Complex Pro — when each wins.",
    xp: 80,
    badge: { slug: "warp-wizard", name: "Warp Wizard" },
    explainer: [
      { kind: "lead", text: "Each Warp Mode uses a different time-stretch algorithm. Picking the wrong one is the #1 cause of 'why does my loop sound mushy?'" },
      { kind: "list", items: [
        "Beats — drums, percussive loops. Locks to transients.",
        "Tones — pitched mono (vocals, bass).",
        "Texture — slow harmonic material (pads, ambient).",
        "Re-Pitch — no stretch; speed AND pitch shift together (vinyl-style).",
        "Complex / Complex Pro — full mixes, vocals; CPU-heavy but cleanest.",
      ]},
      { kind: "callout", tone: "key", text: "Drums → Beats. Vocals → Complex Pro. Mixes → Complex Pro. DJ pitch effect → Re-Pitch." },
    ],
    sim: { type: "warp-lab" },
    quiz: [
      { q: "Best Warp Mode for drums?", options: ["Beats", "Tones", "Texture"], answer: 0 },
      { q: "Vinyl-style speed+pitch shift?", options: ["Re-Pitch", "Complex Pro", "Beats"], answer: 0 },
      { q: "Cleanest for vocals?", options: ["Complex Pro", "Beats", "Re-Pitch"], answer: 0 },
    ],
  },
  {
    slug: "ableton-link-sync",
    world: "performance",
    number: 53,
    title: "Ableton Link in Practice",
    tagline: "Network-sync your Lives, iOS apps, hardware.",
    xp: 70,
    badge: { slug: "linked", name: "Linked" },
    explainer: [
      { kind: "lead", text: "Link is wireless tempo and beat-phase sync over local network. No master, no slave — every peer is equal." },
      { kind: "list", items: [
        "Click the LINK button next to the metronome — same WiFi peers see each other.",
        "Tempo changes propagate live; downbeat phase stays locked.",
        "Optional Start Stop sync makes transports follow each other.",
      ]},
      { kind: "callout", tone: "tip", text: "Two laptops on a phone hotspot is enough to jam — no audio cables needed." },
    ],
    sim: { type: "session-grid" },
    quiz: [
      { q: "Link uses…", options: ["Local network", "MIDI cable", "Audio cable"], answer: 0 },
      { q: "Master/slave model?", options: ["Yes", "No — peer-to-peer"], answer: 1 },
      { q: "Start Stop sync is…", options: ["Optional add-on to Link", "Always on", "Separate protocol"], answer: 0 },
    ],
  },
  {
    slug: "push3-workflow",
    world: "performance",
    number: 54,
    title: "Push 3 Workflow",
    tagline: "Make a track without touching the mouse.",
    xp: 90,
    badge: { slug: "push-fluent", name: "Push Fluent" },
    explainer: [
      { kind: "lead", text: "Push 3 puts pads, screens, encoders and (in Standalone) the whole computer into one unit. The grid mirrors the device under your cursor." },
      { kind: "list", items: [
        "Melodic mode — pads tuned to the chosen scale; wrong notes are physically absent.",
        "Drum mode — bottom-left 4×4 = pads, rest = step sequencer for the selected pad.",
        "Note mode + 64 pads — full melodic step sequencer.",
        "Standalone runs Live's engine inside Push for laptop-free shows.",
      ]},
      { kind: "callout", tone: "key", text: "Push isn't a controller — it's the same Live, with a body." },
    ],
    sim: { type: "drum-pad" },
    quiz: [
      { q: "Push 3 Standalone runs…", options: ["Live's engine internally", "Only MIDI", "Only audio"], answer: 0 },
      { q: "Melodic mode hides…", options: ["Out-of-scale notes", "Drums", "Velocity"], answer: 0 },
      { q: "Drum mode dedicates how many pads to step seq?", options: ["48", "16", "8"], answer: 0 },
    ],
  },
  {
    slug: "macro-variations",
    world: "performance",
    number: 55,
    title: "Macro Variations",
    tagline: "Snapshot, recall, morph — patches that perform.",
    xp: 70,
    badge: { slug: "morpher", name: "Morpher" },
    explainer: [
      { kind: "lead", text: "Macro Variations save the current 16 macro values as a snapshot. Recall by clicking; morph by interpolating between snapshots." },
      { kind: "list", items: [
        "Set the macros, hit New Variation — that's snapshot 1.",
        "Tweak macros, save again — snapshot 2.",
        "Click between them: instant recall. Drag the morph slider: smooth blend.",
      ]},
      { kind: "callout", tone: "tip", text: "Build intro / verse / drop variations on a single Rack — one click changes the song's whole sound." },
    ],
    sim: { type: "knob-trainer" },
    quiz: [
      { q: "Variations save…", options: ["Macro values", "Audio clips", "Tempo"], answer: 0 },
      { q: "Macros per Rack (Live 11+)?", options: ["8", "16", "32"], answer: 1 },
      { q: "Live 12 morph between variations is…", options: ["Smooth interpolation", "Step-only", "Random"], answer: 0 },
    ],
  },
];

export const MISSIONS: Mission[] = [...w1, ...w2, ...w3, ...w4, ...w5, ...w6, ...wExtra];

export const missionsByWorld = (world: string) =>
  MISSIONS.filter((m) => m.world === world).sort((a, b) => a.number - b.number);

export const missionBySlug = (slug: string) => MISSIONS.find((m) => m.slug === slug);

export const nextMission = (slug: string) => {
  const i = MISSIONS.findIndex((m) => m.slug === slug);
  return i >= 0 && i < MISSIONS.length - 1 ? MISSIONS[i + 1] : null;
};

export const prevMission = (slug: string) => {
  const i = MISSIONS.findIndex((m) => m.slug === slug);
  return i > 0 ? MISSIONS[i - 1] : null;
};
