import type { World } from "./types";

export const WORLDS: World[] = [
  {
    slug: "foundations",
    number: 0,
    title: "Music Foundations",
    tagline: "Sound, rhythm, melody, harmony, music tech — from absolute zero.",
    color: "acid",
    description: "Everything you need to know before you touch a DAW or a DJ controller. 40 missions across 5 paths.",
  },
  {
    slug: "dj",
    number: 9,
    title: "DJ World",
    tagline: "Beatmatching, the mix, performance, the crowd.",
    color: "volt",
    description: "From setting up your first rig to reading a crowd at peak hour. 40 missions built from the rekordbox manual.",
  },
  {
    slug: "synths",
    number: 10,
    title: "Synth World",
    tagline: "Build any sound from oscillators, filters, envelopes and LFOs.",
    color: "hot",
    description: "How a synth actually makes noise — and how to bend that noise into bass, leads, pads and plucks. 18 missions across 3 paths.",
  },
  {
    slug: "first-contact",
    number: 1,
    title: "First Contact",
    tagline: "Boot up. Learn the room.",
    color: "acid",
    description: "What Live is, the interface, the browser, preferences, files.",
  },
  {
    slug: "two-views",
    number: 2,
    title: "The Two Views",
    tagline: "Session vs Arrangement. Clips. Scenes.",
    color: "hot",
    description: "Live's twin workflows for jamming and composing.",
  },
  {
    slug: "midi-audio",
    number: 3,
    title: "MIDI & Audio",
    tagline: "Notes. Samples. Warping. Recording.",
    color: "volt",
    description: "Get sound in. Get sound right.",
  },
  {
    slug: "devices",
    number: 4,
    title: "Devices",
    tagline: "Synths, samplers, effects, racks.",
    color: "sun",
    description: "Make sound. Bend sound. Stack sound.",
  },
  {
    slug: "mixing",
    number: 5,
    title: "Mixing & Routing",
    tagline: "Faders. Sends. Automation. Sidechain.",
    color: "acid",
    description: "Glue the track. Move the parts. Hit hard.",
  },
  {
    slug: "performance",
    number: 6,
    title: "Performance",
    tagline: "Push, MIDI, Link, CV, Export.",
    color: "hot",
    description: "Take it out of the box. Play it live. Ship it.",
  },
  {
    slug: "midi-instruments",
    number: 7,
    title: "MIDI & Instruments",
    tagline: "Synths, samplers, racks. Make sound from scratch.",
    color: "volt",
    description: "Tour every built-in instrument. Layer, stack, modulate. Turn MIDI into a voice.",
  },
  {
    slug: "live12-power",
    number: 8,
    title: "Live 12 Power Tools",
    tagline: "Stem split, MIDI transforms, scale, similarity.",
    color: "sun",
    description: "The Live 12 marquee features — the ones that make this version a step-change.",
  },
];
