/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as TrainRouteImport } from './routes/train'
import { Route as SignalFlowRouteImport } from './routes/signal-flow'
import { Route as ShortcutsRouteImport } from './routes/shortcuts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as MatchRouteImport } from './routes/match'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldSlugRouteImport } from './routes/world.$slug'
import { Route as PathSlugRouteImport } from './routes/path.$slug'
import { Route as MissionSlugRouteImport } from './routes/mission.$slug'
import { Route as DeviceSlugRouteImport } from './routes/device.$slug'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalFlowRoute = SignalFlowRouteImport.update({
  id: '/signal-flow',
  path: '/signal-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortcutsRoute = ShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldSlugRoute = WorldSlugRouteImport.update({
  id: '/world/$slug',
  path: '/world/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PathSlugRoute = PathSlugRouteImport.update({
  id: '/path/$slug',
  path: '/path/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionSlugRoute = MissionSlugRouteImport.update({
  id: '/mission/$slug',
  path: '/mission/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceSlugRoute = DeviceSlugRouteImport.update({
  id: '/device/$slug',
  path: '/device/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/paths': typeof PathsRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/shortcuts': typeof ShortcutsRoute
  '/signal-flow': typeof SignalFlowRoute
  '/train': typeof TrainRoute
  '/worlds': typeof WorldsRoute
  '/device/$slug': typeof DeviceSlugRoute
  '/mission/$slug': typeof MissionSlugRoute
  '/path/$slug': typeof PathSlugRoute
  '/world/$slug': typeof WorldSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/paths': typeof PathsRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/shortcuts': typeof ShortcutsRoute
  '/signal-flow': typeof SignalFlowRoute
  '/train': typeof TrainRoute
  '/worlds': typeof WorldsRoute
  '/device/$slug': typeof DeviceSlugRoute
  '/mission/$slug': typeof MissionSlugRoute
  '/path/$slug': typeof PathSlugRoute
  '/world/$slug': typeof WorldSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/paths': typeof PathsRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/shortcuts': typeof ShortcutsRoute
  '/signal-flow': typeof SignalFlowRoute
  '/train': typeof TrainRoute
  '/worlds': typeof WorldsRoute
  '/device/$slug': typeof DeviceSlugRoute
  '/mission/$slug': typeof MissionSlugRoute
  '/path/$slug': typeof PathSlugRoute
  '/world/$slug': typeof WorldSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices'
    | '/glossary'
    | '/login'
    | '/match'
    | '/paths'
    | '/playground'
    | '/profile'
    | '/shortcuts'
    | '/signal-flow'
    | '/train'
    | '/worlds'
    | '/device/$slug'
    | '/mission/$slug'
    | '/path/$slug'
    | '/world/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devices'
    | '/glossary'
    | '/login'
    | '/match'
    | '/paths'
    | '/playground'
    | '/profile'
    | '/shortcuts'
    | '/signal-flow'
    | '/train'
    | '/worlds'
    | '/device/$slug'
    | '/mission/$slug'
    | '/path/$slug'
    | '/world/$slug'
  id:
    | '__root__'
    | '/'
    | '/devices'
    | '/glossary'
    | '/login'
    | '/match'
    | '/paths'
    | '/playground'
    | '/profile'
    | '/shortcuts'
    | '/signal-flow'
    | '/train'
    | '/worlds'
    | '/device/$slug'
    | '/mission/$slug'
    | '/path/$slug'
    | '/world/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesRoute: typeof DevicesRoute
  GlossaryRoute: typeof GlossaryRoute
  LoginRoute: typeof LoginRoute
  MatchRoute: typeof MatchRoute
  PathsRoute: typeof PathsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProfileRoute: typeof ProfileRoute
  ShortcutsRoute: typeof ShortcutsRoute
  SignalFlowRoute: typeof SignalFlowRoute
  TrainRoute: typeof TrainRoute
  WorldsRoute: typeof WorldsRoute
  DeviceSlugRoute: typeof DeviceSlugRoute
  MissionSlugRoute: typeof MissionSlugRoute
  PathSlugRoute: typeof PathSlugRoute
  WorldSlugRoute: typeof WorldSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal-flow': {
      id: '/signal-flow'
      path: '/signal-flow'
      fullPath: '/signal-flow'
      preLoaderRoute: typeof SignalFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortcuts': {
      id: '/shortcuts'
      path: '/shortcuts'
      fullPath: '/shortcuts'
      preLoaderRoute: typeof ShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/$slug': {
      id: '/world/$slug'
      path: '/world/$slug'
      fullPath: '/world/$slug'
      preLoaderRoute: typeof WorldSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/$slug': {
      id: '/path/$slug'
      path: '/path/$slug'
      fullPath: '/path/$slug'
      preLoaderRoute: typeof PathSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/$slug': {
      id: '/mission/$slug'
      path: '/mission/$slug'
      fullPath: '/mission/$slug'
      preLoaderRoute: typeof MissionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/$slug': {
      id: '/device/$slug'
      path: '/device/$slug'
      fullPath: '/device/$slug'
      preLoaderRoute: typeof DeviceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesRoute: DevicesRoute,
  GlossaryRoute: GlossaryRoute,
  LoginRoute: LoginRoute,
  MatchRoute: MatchRoute,
  PathsRoute: PathsRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProfileRoute: ProfileRoute,
  ShortcutsRoute: ShortcutsRoute,
  SignalFlowRoute: SignalFlowRoute,
  TrainRoute: TrainRoute,
  WorldsRoute: WorldsRoute,
  DeviceSlugRoute: DeviceSlugRoute,
  MissionSlugRoute: MissionSlugRoute,
  PathSlugRoute: PathSlugRoute,
  WorldSlugRoute: WorldSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
